### ISSUE TITLE
Determine best way to handle GPS offsets

### ISSUE THREAD

**Issue by ayrton04** [cra-ros-pkg/robot_localization#114]
A GPS device could be mounted anywhere on a vehicle. The standard practice when a sensor is placed somewhere on a vehicle is to define a transform from base_link->sensor. Ordinarily, this works well, as sensor measurements are actually retrieved in the sensor frame (e.g., a LIDAR returns points whose distances are w.r.t. the sensor itself). 

GPS devices obviously do not work this way. They are mounted at some location on the vehicle, but report data in a world-fixed frame. This means that if our GPS sensor's offset from the base_link frame is defined by a base_link->gps transform, we cannot simply apply that transform to transform a GPS reading and expect it to actually gives the GPS location of the vehicle's center point. 

As I see it, we have two options:

1. Let users define a base_link->gps transform, but instead of applying it in the typical fashion (i.e., via tf transformPose function calls), just take the X/Y/Z offset as defined in the transform, rotate it by the vehicle's current map frame orientation, and remove that offset from the latest GPS measurement coming from navsat_transform_node (which will already have been transformed into the map frame). 

2. Add a parameter to navsat_transform_node that defines only the X/Y/Z offset from the vehicle center (orientation of the GPS sensor is irrelevant). Use that data in the same fashion as in (1).

The former lets people use the tf tree as they would expect, but may cause confusion. The latter adds new parameters that have to be filled out, and it may be unclear to users as to why we're not use existing ROS functionality.

I'd welcome comments/suggestions...

**Comment by ayrton04** [comment]
I think this is related to issue #203, but I'm not certain I can push all the logic to the state estimation nodes and leave `navsat_transform_node` untouched. TBD...

**Comment by ayrton04** [comment]
I'm working on this as time allows.

**Comment by ayrton04** [comment]
Done. If anyone has any test data in which their GPS is mounted far from the vehicle's origin, I'd appreciate either taking a look at that data so I can test this more thoroughly (or feel free to test it yourself). You just need to make sure you define the GPS offset as base_link (or whatever your body frame ID is ) to gps (or whatever your navsat device frame ID is).

**Comment by Masoumehrahimi** [comment]
hi @ayrton04
my gps is situated on a tower, on the vehicle,that there is distance between the base_link and GPS, but as i check the tf tree i have GPS_link in my tf tree, and as i run: rosrun tf tf_echo base_link gps_link , it starts publishing data, which means there is a connection between them, so in this case, do i need to again define the distance between them??
if yes, why? and what is the easiest way?
thanks

**Comment by ayrton04** [comment]
answers.ros.org, please
