### ISSUE TITLE
Metric scale estimation in monocular system

### ISSUE THREAD

**Issue by mhkabir** [cra-ros-pkg/robot_localization#123]
Hi Guys, 

We're using the rpg_svo stack for monocular visual odometry. We also have an IMU for estimating the metric scale. Previously, we've used the ethzasl_msf ekf framework for the sensor fusion and scaling, but now I'd like to try out this package. 

Ethzasl_msf automatically scales the measurement from SVO using IMU data (common movement) and the output has correct metric scale. Is this implemented in your package? If so, are there any specific steps or parameters required to be set? If not, how difficult would implementation be?

**Comment by deepak-1530** [comment]
I am working on the implementation of svo and need to estimate the scale. How can I do that using pixhawk?

**Comment by ayrton04** [comment]
Please direct questions to answers.ros.org, thank you.
