### ISSUE TITLE
Node crashes on startup

### ISSUE THREAD

**Issue by mhkabir** [cra-ros-pkg/robot_localization#125]
The EKF localisation node is crashing right on launch :

```
process[ekf_localization-3]: started with pid [10649]
ekf_localization_node: malloc.c:3695: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
```

ROS Indigo on Ubuntu 14.04 LTS

**Comment by sozgundemir** [comment]
I'm having the same problem when I try running the ekf_localization_node in ROS-Groovy. However, the same node works fine in ROS-Kinetic. How did you solve the problem?

**Comment by ayrton04** [comment]
Are you building from source?

**Comment by sozgundemir** [comment]
In both computers I just downloaded the relevant version of the package from github.

**Comment by ayrton04** [comment]
I'm afraid I don't have a Groovy setup with which to replicate this. You may want to try cloning older versions to see if they all produce the same issue. If you find one that doesn't, I can do a diff and see what's changed. For what architecture are you building?

**Comment by sozgundemir** [comment]
I'm working on a custom made automated vehicle system, and trying to use this node for gps, odometry and imu sensors.

**Comment by ayrton04** [comment]
OK, so ARM? x86? x86_64? Or would you rather not say?

**Comment by sozgundemir** [comment]
Sorry I misunderstood your question. It is X86_64

**Comment by ayrton04** [comment]
Interesting. At first glance it sounds like a dependency issue somewhere. I take it you need to use Groovy?

**Comment by sozgundemir** [comment]
If solving the problem is not possible I may think about upgrading to Kinetic.

**Comment by ayrton04** [comment]
I don't have an answer off the top of my head, I'm afraid, other than to make sure all your dependencies are updated to the latest version(s) possible.
