### ISSUE TITLE
Option to future date map->odom transformation

### ISSUE THREAD

**Issue by IvanVN** [cra-ros-pkg/robot_localization#153]
Would it be possible to add an option to future date the resulting transformation from the ekf_localization_node?

I'm trying to use robot_localization along with move_base, but move_base requires that the map->odom transform to be future dated. Global positioning packages like gmapping or AMCL do future date this transformation.

It would be interesting to add the posibility to optionally future date the obtained transformation when using robot_localization as a source for global localization. It would greatly help it's integration with the standar ROS navigation stack.

Thank you and best regards.

**Comment by ayrton04** [comment]
Sure, we can do that. Question: do amcl and gmapping future date by default? Also, is it an option for those packages, or does it always future date?

**Comment by paulbovbel** [comment]
by default:

amcl future dates transforms by 0.1 seconds
gmapping future dates by the transform_publish_period, which is 0.05 seconds by default. somewhat undocumented.

**Comment by ayrton04** [comment]
Moving this to the top of my queue.

**Comment by ayrton04** [comment]
Added a `transform_time_offset` parameter which specifies, in seconds, the amount of time to add to the transform's timestamp. For backwards compatibility, it defaults to 0. I still need to update the launch file templates to reflect the change.
