### ISSUE TITLE
Calling set_pose with worldframe = map is incorrectly transformed

### ISSUE THREAD

**Issue by servos** [cra-ros-pkg/robot_localization#168]
The general problem I am seeing is that when I call "set_pose" to the EKF the state gets set incorrectly. I'm unsure if this is a bug or if I may simply have my ekf configured incorrectly.

My frames are the standard:
map_frame: map
world_frame: map
odom_frame: odom

What I am seeing is if I send a /set_pose with a frame_id of map then I expect the output of the filter to be what I set in the set_pose message. Instead what I see is that it gets transformed by the odom->map transform before being set.

Looking through the code I found in ros_filter.cpp, line 1265:  
preparePose(msg, topicName, odomFrameId_, false, false, false, updateVector, measurement, measurementCovariance);

which is using the odomFrameId_ for the transform. By changing this to worldFrameId_, everything works as expected.

It seems odd that the filter is transforming into the odom frame. If this is intended then I am not sure what I am doing wrong.

Thanks!

**Comment by ayrton04** [comment]
That's a bug. Nice catch. Would you mind submitting a PR for that?

**Comment by ayrton04** [comment]
Fixed with merge of #169.
