### ISSUE TITLE
Covariance override

### ISSUE THREAD

**Issue by ayrton04** [cra-ros-pkg/robot_localization#18]
Users don't always have control over the nodes that produce sensor data. Many sensors indicate the absence of measurement of a given variable by inflating its covariance to an extremely large number. A Kalman filter based approach will apply a very small weight to such a measurement, effectively ignoring it. However, it is sometimes the case that even if a sensor does not measure a variable, it should be included as part of its measurements. For example, a robot that operates in a planar environment will produce 0 measurements for Z and Z velocity. Rather than giving these values a large covariance value, it makes sense to make the covariance for those variable very small and integrate the 0 values. To give users greater control over input data, a new (set of) parameter(s) should be added to allow the users to manually override a sensor's covariance values.

**Comment by ayrton04** [comment]
Dropping this this, as the combination of diagnostics and handling of poor covariances should be sufficient. Users should instead focus on fixing the source of bad covariance data.

**Comment by ghost** [comment]
It's been a couple of years, but has this issue been reopened and implemented? I am trying to make sure I am not missing anything.

Thanks!

**Comment by ayrton04** [comment]
No, it hasn't. I decided, in the end, that it made more sense for users to make sure their data was correct, rather than relying on the EKF to override anything.

**Comment by mbudris** [comment]
As you said "Users don't always have control over the nodes that produce sensor data.". How people overcome the particular case of inflated Z_vel covariance these days? Because the robot takes off immediately. I'd like to have the two_d_mode set to false, since the robot will be operating at slopes.

**Comment by ayrton04** [comment]
Please ask this question on answers.ros.org. When you do, please provide details of your robot, the problem, and sample sensor messages.

**Comment by ayrton04** [comment]
Also, I'd note that this would require a code change for `r_l`, or it would require a code change for the node that produces the sensor data. As long as we're changing code, why not fix the driver?

**Comment by mbudris** [comment]
> 
> 
> Please ask this question on answers.ros.org. When you do, please provide details of your robot, the problem, and sample sensor messages.

I will, after I'll read all the q&a to not to make duplicates. There should be a workaround since r_l lives for long time now.
