### ISSUE TITLE
Robot Localization Position Freeze

### ISSUE THREAD

**Issue by nanohaddad** [cra-ros-pkg/robot_localization#243]
My position freezes at arbitrary units (more often around 14-20 meters). My orientation, twist, and covariance values continue to update; however the pose position does not. I've checked and the odometry topic is still constantly updating- anyone else having a similar issue?

**Comment by ayrton04** [comment]
Interesting. I've never seen that happen. Which version are you using? Can you post a bag file somewhere? I'd also be curious to see sample input messages from before and after the freeze.

**Comment by ayrton04** [comment]
Any update on this?
