### ISSUE TITLE
Could not find a package configuration file provided by "geographic_msgs"

### ISSUE THREAD

**Issue by JinglinZhang** [cra-ros-pkg/robot_localization#245]
When I build the robot_localization package from source, I got a CMake Error like this:

```
-- ==> add_subdirectory(robot_localization)
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
  Could not find a package configuration file provided by "geographic_msgs"
  with any of the following names:

    geographic_msgsConfig.cmake
    geographic_msgs-config.cmake

  Add the installation prefix of "geographic_msgs" to CMAKE_PREFIX_PATH or
  set "geographic_msgs_DIR" to a directory containing one of the above files.
  If "geographic_msgs" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  robot_localization/CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/siat/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/siat/catkin_ws/build/CMakeFiles/CMakeError.log".
make: *** [cmake_check_build_system] 错误 1
Invoking "make cmake_check_build_system" failed

```

Could anyone help me?

**Comment by ayrton04** [comment]
`sudo apt-get install ros-indigo-geographic-msgs`

You can also try `rosdep install robot_localization`

**Comment by JinglinZhang** [comment]
@ayrton04 It's great! The command  `sudo apt-get install ros-indigo-geographic-msgs` solve the problem. Thank you very much!

**Comment by kumarrt** [comment]
I was getting the same error, I tried `sudo apt-get install ros-kinetic-geographic-msgs` and it worked.

**Comment by ayrton04** [comment]
If you have a catkin workspace and are building any code from source, your first step should always be

```
cd /your/catkin/workspace/root
rosdep install --from-paths src --ignore-src
```

This will automatically install all required binary dependencies for the packages in your workspace.

**Comment by VictorBLop** [comment]
Thank you very much, the first idea solved the problem for me.

**Comment by zeelbhatt** [comment]
I installed all dependencies using `rosdep install --from-paths src --ignore-src` 

but still have same problem

**Comment by shivamkainth** [comment]
> I installed all dependencies using `rosdep install --from-paths src --ignore-src`
> 
> but still have same problem

Check for your ROS version, it could be noetic, kinetic or melodic and accordingly change the apt-get isntall command 
For my case it was `sudo apt-get install ros-noetic-geographic-msgs ` for ros on ubuntu 20.04

**Comment by VictorBLop** [comment]
Thanks, Shivam.

Best regards.

**Comment by cl12312** [comment]
1
