### ISSUE TITLE
Robot Monitor gives an error, how to set imu0_pose_covariance?

### ISSUE THREAD

**Issue by cosmicog** [cra-ros-pkg/robot_localization#246]
Hi, Robot Monitor says: 

> **imu0_pose_covariance:** The covariance at position (35), which
> corresponds to YAW variance, was zero.
> This will be replaced with a small
> value to maintain filter stability,
> but should be corrected at the message
> origin node.

I've set this under ekf_localization tag in my controls.yaml file;

```
     ...
     ekf_localization:
       ...
       imu0_pose_covariance: [1e-5, 0.0, 0.0, 0.0, 0.0, 0.0,
                              0.0, 1e-5, 0.0, 0.0, 0.0, 0.0,
                              0.0, 0.0, 1e-5, 0.0, 0.0, 0.0,
                              0.0, 0.0, 0.0, 1e-5, 0.0, 0.0,
                              0.0, 0.0, 0.0, 0.0, 1e-5, 0.0,
                              0.0, 0.0, 0.0, 0.0, 0.0, 1e-5]
       ...
```

But still no effect. How can I set this? Or How can I correct this problem?

**Comment by ayrton04** [comment]
Measurement covariances are not a setting for `ekf_localization_node`. They come from the measurements themselves. See the [sensor_msgs/Imu](http://docs.ros.org/api/sensor_msgs/html/msg/Imu.html) definition.
