### ISSUE TITLE
Interfacing with RTABMAP

### ISSUE THREAD

**Issue by zastrix** [cra-ros-pkg/robot_localization#254]
Hello,

I am working to use robot_localization to take in info from a piksi gps, rp 2d lidar, and UM7 IMU and to give me a good estimate of where I am in space. I want to report this to rtabmap so I can relate this position to the 3d environment of my robot. When I run rtabmap without robot_localization everying works, however when I run robot_localization alongside rtabmap the odom frame drifts like crazy. I didn't know if this was an issue that you have seen before or not. Let me know what you need from me!

**Comment by ayrton04** [comment]
Was this asked on ROS answers already?

**Comment by zastrix** [comment]
I did not post it nor did I find someone that had :100: Would you like me to put it there?

**Comment by ayrton04** [comment]
Would you mind posting it there? This board should really be for actual bugs or feature requests.
