### ISSUE TITLE
Navsat_transform_node input

### ISSUE THREAD

**Issue by ghost** [cra-ros-pkg/robot_localization#259]
Hello,

the question is relatively simple. I try to use the package but i have some doubts about navsat node. In tutorial, it is explained that the input are:
- sensor_msgs/NavSatFix
- sensor_msgs/Imu
-  nav_msgs/Odometry.

The question is: odometry message is normally the output of robot_localization state estimation node, but  this node is that fuse odom and imu data ( continous data) or it is that fuse odom_from_gps,imu and odom? 

Thanks.

**Comment by ayrton04** [comment]
Hi! Would you mind posting this on ROS Answers? I'm trying to keep the issues here focused on bugs and feature requests. If you already posted the question, can you kindly direct me to it? Thanks!
