### ISSUE TITLE
Allow to dynamically reconfigure the process noise

### ISSUE THREAD

**Issue by falkoschindler** [cra-ros-pkg/robot_localization#260]
There are situations where the process noise might change while the Kalman filter is running. This is, e.g., when the robot stops and knows precisely that it's standing still. Then we'd like to see no error growth in the filtered pose. See this post for more background information: http://answers.ros.org/question/227775/how-to-fix-the-ekf-pose-when-the-robot-is-definitely-not-moving/

I guess, making the process noise covariance matrix a dynamically reconfigurable parameter would solve this issue.

**Comment by ayrton04** [comment]
This has become a higher priority. Here's a branch that computes the process noise covariance for pose variables dynamically:

https://github.com/cra-ros-pkg/robot_localization/tree/dynamic-process-noise

I'm debating simplifying it a bit and just using the linear velocity to scale the pose process noise covariance. As it is now, I'm doing that, but I'm using the covariance block for the twist variables and rotating it.
