### ISSUE TITLE
Subscribe data with tcpNoDelay()

### ISSUE THREAD

**Issue by jbler** [cra-ros-pkg/robot_localization#276]
Hi,

I am running the EKF at 200 Hz. At that frequency I am not able to get every spin a new measurement but my subscribing measurement is sent a 200 Hz. Instead my data is often arriving at bunches of a few measurments together and therefore with a lower frequency.  

Would it be possible to subscribe a topic  using the ros::TransportHints().tcpNoDelay() option which seems a reasonable try for me.

**Comment by ayrton04** [comment]
Have you tried increasing the queue size for the sensor in question?

**Comment by ayrton04** [comment]
But the short answer is that yes, I think it would be a good idea. Would you be willing to fork the repo and try it?

**Comment by jbler** [comment]
Thanks for the fast reply. 
Sure, I will give it a try later!
