### ISSUE TITLE
after update to new code, roslaunch occurs python running error..

### ISSUE THREAD

**Issue by asimay** [cra-ros-pkg/robot_localization#283]
after update to new code, roslaunch occurs python running error..
old version has no such warning.
if i comment the include" ekf launch file", the warning disappeared. so some params reading maybe have some issues.
![3333](https://cloud.githubusercontent.com/assets/8703449/15701386/8a2aa11a-280c-11e6-8f3c-e6136676d81c.png)

**Comment by asimay** [comment]
launch file:
![00](https://cloud.githubusercontent.com/assets/8703449/15701549/78016806-280d-11e6-9853-cbc36a936952.png)

**Comment by ayrton04** [comment]
Are you using the template directly, or have you modified it? Any chance you can try removing parameters until the warning disappears?

**Comment by asimay** [comment]
hi, dear @ayrton04 , I re-download the new version and use new version's code totally, the warning disappered. but actually my version looks no difference with new version except a little of comments, and i used binary tool "bccompare" to look up the difference, but find nothing. it is very strange. but anyway,  Thank you very much!
