### ISSUE TITLE
Nodelet support

### ISSUE THREAD

**Issue by asimay** [cra-ros-pkg/robot_localization#285]
enhancement advise: due to large quantity data iput, the module should use "nodelet" to avoid data copy and improve the performance.
Please consider this suggestion. Thanks!

**Comment by SGSSGene** [comment]
@asimay I'm trying to implement nodelets in PR #343 . The implemented test doesn't work. Maybe you have any Idea why?

**Comment by SGSSGene** [comment]
No worries. Found the error. Going to fix everything and hopefully send a PR for nodelets soon.

**Comment by ayrton04** [comment]
Addressed in #343
