### ISSUE TITLE
Navsat_transform_node never take imu_topic into account.

### ISSUE THREAD

**Issue by asimay** [cra-ros-pkg/robot_localization#290]
snapshot as belows:
Navsat_transform_node never take imu_topic into account. 
![22](https://cloud.githubusercontent.com/assets/8703449/16035828/c19e072e-324b-11e6-8a5d-f436dcc0f15d.png)

```
      <remap from="/imu/data" to="imu_topic"/>
      <remap from="/gps/fix" to="imu_nav_topic"/>
      <remap from="/odometry/filtered" to="odom_filtered_gps"/>
```

and no matter I set:
`<param name="use_odometry_yaw" value="true"/>`
or
`<param name="use_odometry_yaw" value="false"/>`

imu_topic is not taken into account.

**Comment by ayrton04** [comment]
Again, this should be a ROS Answers question, and we should verify that there is a problem before posting an issue. In this case, the IMU subscription is only needed until a single IMU message is received, at which point the subscriber is taken down:

https://github.com/cra-ros-pkg/robot_localization/blob/indigo-devel/src/navsat_transform.cpp#L198

**Comment by asimay** [comment]
hi, dear @ayrton04 : 
Thank you very much! But when I set 
`<param name="use_odometry_yaw" value="false"/>`
terminal occurs such errors: 

![33](https://cloud.githubusercontent.com/assets/8703449/16036469/b38fe03c-324e-11e6-917d-d044f2857305.png)

**Comment by ayrton04** [comment]
Looks like a ROS answers question. Please post your configuration and sample input messages.
