### ISSUE TITLE
Absolute odometer offset not handled.

### ISSUE THREAD

**Issue by nznobody** [cra-ros-pkg/robot_localization#299]
Hello,
I think this is worth raising here as an issue. [Original ROS Answers Question](http://answers.ros.org/question/239326/sensor-frame-offset-for-robot_localization-absolute-odometer-offset/)  

I am unable to handle an original odometry offset correctly with the robot_localization package.

**Comment by ayrton04** [comment]
Were you ever able to figure this out?

**Comment by nznobody** [comment]
@ayrton04 : guilty as charged with not posting my solution! I have 'solved' it in a way. Explanation posted on [ROS Answers](http://answers.ros.org/question/239326/sensor-frame-offset-for-robot_localization-absolute-odometer-offset/?answer=255199#post-id-255199)
