### ISSUE TITLE
navsat_transform_node /odometry/gps position [nan nan nan]

### ISSUE THREAD

**Issue by hityrj** [cra-ros-pkg/robot_localization#313]
Hello Sir, 
I am trying to us the robot_localization package to localize a robot with a IMU and a GPS. However, the output of the navsat_transform_node is either 0 or NAN. The output are as follows:
header: 
  seq: 984
  stamp: 
    secs: 1477132455
    nsecs: 663983949
  frame_id: odom
child_frame_id: ''
pose: 
  pose: 
    position: 
      x: nan
      y: nan
      z: nan
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  covariance: [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
twist: 
  twist: 
    linear: 
      x: 0.0
      y: 0.0
      z: 0.0
    angular: 
      x: 0.0
      y: 0.0
      z: 0.0
  covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

The output of IMU is as follows:
header: 
  seq: 6362
  stamp: 
    secs: 1477132388
    nsecs: 539831258
  frame_id: imu
orientation: 
  x: 0.0
  y: 0.0
  z: 0.0
  w: 0.0
orientation_covariance: [-1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: 0.0125460391864
  y: -0.000657466240227
  z: 0.0173181127757
angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
  x: 1.37939727925
  y: 0.472430611119
  z: -9.98167572752
linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

The output of GPS is as follows:
yrj@MANNY:~/map_yrj$ rostopic echo /mavros/global_position/global
header: 
  seq: 595
  stamp: 
    secs: 1477132384
    nsecs: 564878072
  frame_id: fcu
status: 
  status: 0
  service: 1
latitude: 1.2997067
longitude: 103.7932783
altitude: 26.9
position_covariance: **[9997.999672796635, 0.0, 0.0, 0.0, 9997.999672796635, 0.0, 0.0, 0.0, 39991.99869118654]**
## position_covariance_type: 1

The values of the covariance matrix for the output of GPS is very huge, is this the main reason which lead to the [nan nan nan] output? 

My launch file for navsat_transform_node:

```
<node pkg="robot_localization" type="navsat_transform_node" name="navsat_transform_node" respawn="true">
        <param name="magnetic_declination_radians" value="0.0036651914"/>
        <param name="yaw_offset" value="0.0"/>
        <param name="zero_altitude" value="false"/>
        <param name="broadcast_utm_transform" value="false"/>
        <param name="publish_filtered_gps" value="true"/>
        <param name="use_odometry_yaw" value="false"/>
        <param name="wait_for_datum" value="false"/>

        <remap from="/imu/data" to="/imu/imu" />
        <remap from="/gps/fix" to="/mavros/global_position/global" />
        <remap from="/odometry/filtered" to="/odometry/filtered" />
    </node>
```

**Comment by ayrton04** [comment]
The issue is that your IMU does not provide orientation data:

```
orientation: 
x: 0.0
y: 0.0
z: 0.0
w: 0.0
```

Please see [this section](http://docs.ros.org/kinetic/api/robot_localization/html/integrating_gps.html#required-inputs) on the wiki. `navsat_transform_node` requires an earth-referenced heading. As such, and IMU that does not have a magnetometer will not work with `navsat_transform_node`. Since `navsat_transform_node` is using the quaternion, and the quaternion is invalid, you end up with a NaN transform.

However, the massive covariance matrix in your GPS data should probably also be addressed.
