### ISSUE TITLE
Expose acceleration state via ROS interface

### ISSUE THREAD

**Issue by reinzor** [cra-ros-pkg/robot_localization#314]
The acceleration state is currently not exposed since the `nav_msgs/Odometry` does not hold the acceleration attribute.

Here: http://www.ros.org/reps/rep-0147.html , people suggested adding an acceleration attribute to the message; however, this would break the current API. An other possibility is exposing the acceleration state via a `geometry_msgs/AccelWithCovarianceStamped` message.

I would like to integrate this into the ROS filter, what do you think about this?

**Comment by ayrton04** [comment]
Sounds like a good idea! Should be pretty straightforward. Just so we don't introduce a new topic for everyone, please make publication optional, with the default parameter value set to false.

**Comment by reinzor** [comment]
OK thanks, I will send a PR later this week.

-Rein

**Comment by ayrton04** [comment]
Merged.
