### ISSUE TITLE
Pose and velocity calculation of frames fixed to the robot

### ISSUE THREAD

**Issue by rokusottervanger** [cra-ros-pkg/robot_localization#326]
For our (automotive) use case, we need to calculate the (poses and) velocities of sensors (fixed to the robot) with respect to the fixed world to be able to track their readings in a world-fixed frame of reference. Their poses can be found using a tf listener, but the velocities depend on this transformation as well as the motion of the robot base, which is estimated using nodes in the robot localization package. 
We feel this is something that other people may also need to do. Especially if they have sensors capable of measuring velocity, such as radar. And we think this would be a nice addition to the robot localization package, wouldn't you agree?

**Comment by ayrton04** [comment]
Sure. Any reason it can't be rolled into your [PR](https://github.com/cra-ros-pkg/robot_localization/pull/324)? The `GetState` service could include a [frame_id](https://github.com/cra-ros-pkg/robot_localization/pull/324/files#diff-eee1a9fe3a42f3ef637b5d48825e4acaR1) in the request.

**Comment by rokusottervanger** [comment]
Sounds good, I'll add it there.

**Comment by ayrton04** [comment]
Merged.
