### ISSUE TITLE
map->odom drifts in z direction with zero altitude set to true

### ISSUE THREAD

**Issue by tuandle** [cra-ros-pkg/robot_localization#330]
I observed the drifting in z direction from map->odom when fusing 2 IMUs (1 IMU reports drifting data and 1 IMU reports good data). This didn't happen if I fuse each IMU separately (meaning, for test 1, I only fused IMU#1, gps, robot's odom; for test 2 IMU#2, gps, robot's odom). 
I already asked the question here: http://answers.ros.org/question/249821/robot_localization-map-odom-drifts-in-z-direction-with-zero-altitude-set-to-true/ several days ago but got no answer. 
Could anyone have any idea how to deal with this?  Thanks in advance!

**Comment by ayrton04** [comment]
Answered on ROS Answers.
