### ISSUE TITLE
navsat_transform_node rounding datum lat lon

### ISSUE THREAD

**Issue by mikehosmar** [cra-ros-pkg/robot_localization#338]
I have specified a fairly accurate ppp datum of [43.9406655, -078.8942039, 0] but I found out later that the node is actually using  (43.940700, -78.894200, 0.000000). In UTM this isn't insignificant (something like 3~4 meters).  Not sure if this can be fixed but I think it's happening near the line I linked.

[navsat_transform.cpp L124](https://github.com/cra-ros-pkg/robot_localization/blob/a7f8bd92489ad4c76fbb5f63f58b22780cde6a11/src/navsat_transform.cpp#L124)

P.S. Are there any other points that the position would be rounded possibly in the UTM calculation? I need to be able to compare the gps odometry to other UTM measurements Ive made.

**Comment by ayrton04** [comment]
Yeah, that's no good. I wonder if parameter reading is reading that type as a float (32-bit), or if the input stream operator also respects things like `std::setprecision`. Thanks for the heads-up.

**Comment by mikehosmar** [comment]
`std::setprecision` sound right. The default precision is what I'm seeing.  So maybe just a `std::setprecision(10)` would be a good fix.

**Comment by ayrton04** [comment]
Care to test it and let me know if it works?

**Comment by ayrton04** [comment]
Fixed in #391.
