### ISSUE TITLE
Problem while integrating GPS data

### ISSUE THREAD

**Issue by GuidoBartoli** [cra-ros-pkg/robot_localization#339]
Dear Tom,
I'm still working on the project involving IMU, encoders as I reported in the previous ticket: 
[https://github.com/cra-ros-pkg/robot_localization/issues/332](url)

Since the local odometry fusion went fine, we are adding GPS data to it, but I reported a problem I'm currently having with navsat_transform and EKF on ROS Answers here (I provided all data to reproduce it): [http://answers.ros.org/question/252997/problem-while-integrating-gps-data-into-robot_localization/](url)

Do you have any idea on why is this happening? Is there something wrong in my setup?

Many thanks,
Guido

**Comment by ayrton04** [comment]
Waiting for the updates to the ROS Answers question. Will handle this there.
