### ISSUE TITLE
Set initial state via parameters

### ISSUE THREAD

**Issue by ayrton04** [cra-ros-pkg/robot_localization#357]
We should enable users to set the filter's initial state via a parameter.

**Comment by ayrton04** [comment]
Fixed in https://github.com/cra-ros-pkg/robot_localization/pull/358.

**Comment by siddharthbhurat4** [comment]
I am trying to set this ros parameter from my python file where I record my initial offsets.
When I check that parameter using rosparam get command from command line, it is giving the correct values, but the filter is not starting at that position. I am using ekf.
This is how I am setting it:

`            rospy.set_param('/initial_state', [x_offset, y_offset, 0.0, 
                                               0.0, 0.0, th_offset,
                                               0.0, 0.0, 0.0,
                                               0.0, 0.0, 0.0,
                                               0.0, 0.0, 0.0])`

**Comment by ayrton04** [comment]
@siddharthbhurat4 please ask questions on answers.ros.org.

**Comment by siddharthbhurat4** [comment]
Hey Tom, I have asked a question on ros answers. Please can you guide me there. 
The name of post is - robot_localization package ros

**Comment by siddharthbhurat4** [comment]
I am having a confusion about the transformations which I should have when using the given config of sensors. Please can you guide me there.

**Comment by ayrton04** [comment]
Can you please just provide a link to the question?

**Comment by siddharthbhurat4** [comment]
https://answers.ros.org/question/415827/robot_localization-package-ros/

**Comment by ayrton04** [comment]
Responded with a comment. You'll need more info in your question.
