### ISSUE TITLE
EKF gets latched to /set_pose service values

### ISSUE THREAD

**Issue by bluehash** [cra-ros-pkg/robot_localization#360]
Hello,
This is my time posting an issue to github. If I'm in the wrong place, please let me know. I've tried to put in as much details and raw data as possible.

Environment: ROS Kinetic/Ubuntu 16.04
robot_localization version: 2.3.1

I've been trying to initialize the EKF to a specific co-ordinate on a map for testing purposes. The documentation suggests using the /set_pose service. But I've been [having trouble with it](http://answers.ros.org/question/258491/help-initializing-ekf-to-a-set-position/).

The input to the EKF are two sensor streams - 

- Odometry calculated from the wheel encoders over /odom
- IMU data passed through a complimentary filter over /imu/data

I've stripped my vehicle bag file to a new bag file called odomImu.bag - [Download](https://www.dropbox.com/sh/e44qgp9s7uerd0b/AACTLmmlyaAKuNB4oVcKYK3Ma?dl=0). This bag contains /odom and /imu/data topics.

I've also attached my ekf parameter file(ekf_template.yaml) and launch file.

1. Start the robot_localization node with the parameter file.
2. Open a window to view EKF data: rostopic echo /odometry/filtered/pose/pose/position
3. Run the bag file: rosbag play odomImu.bag
4. Set pose:
`rosservice call /set_pose "pose:
  header:
    seq: 0
    stamp: now
    frame_id: odom
  pose:
    pose:
      position: {x: 1.0, y: 1.0, z: 0.0}
      orientation: {x: 0.0, y: 0.0, z: 0.0, w: 0.0}
    covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]"`

When you /set_pose, /odometry/filtered/pose gets set to x=1, y=1, but then never changes as the bag plays. The vehicle starts moving around the 15 second mark, so you have to wait for a few seconds or monitor /odom via rostopic echo /odom/pose/pose/position

The reason why I'm this stage is because I was not able to get /set_pose to work when odom0_differential was set to false.

**Comment by ayrton04** [comment]
I'm going to address this on ROS Answers and will reopen if this is a bug.
