### ISSUE TITLE
Feature Request : Support for 9 dimensional Navigation state

### ISSUE THREAD

**Issue by kshitijgoel007** [cra-ros-pkg/robot_localization#362]
Hello everyone,

Thanks for maintaining this package. I wish to know if this only works for a 15-dimensional state only? If yes,  can we modify the YAML in order to obtain a 9-dimensional setup?

I am trying to use this package for use in an underwater vehicle. My navigation state vector is  : [x y z theta psi phi u v w]

Awaiting your response!

Best,
Kshitij

**Comment by ayrton04** [comment]
Is there a [ROS answers question](http://answers.ros.org/questions/) for this? If so, can you please point me to it?

Just so we're clear, what does the vector `[u v w]` represent in this case?

As it is, the filter tracks a 15-D state of the vehicle, but that doesn't mean you have to use all of the information. Fuse what data you have and read out what you need. The output is a [nav_msgs/Odometry](http://docs.ros.org/api/nav_msgs/html/msg/Odometry.html) message, which contains pose and velocity.

**Comment by ayrton04** [comment]
Can this be closed, or are you still requiring functionality that the package lacks?

**Comment by ayrton04** [comment]
Closing. Feel free to discuss further and I will re-open if needed.
