### ISSUE TITLE
pub no data after running rosrun

### ISSUE THREAD

**Issue by DaDaDoDoLee** [cra-ros-pkg/robot_localization#365]
Data flows normally after running  roslaunch ekf_template.launch（with test2.bag playing background）,while nothing happens after rosrun robot_localization ekf_localization_node.
Any answer would be appreciated.

**Comment by ayrton04** [comment]
You're likely to get some better answers if you ask questions on answers.ros.org. This particular question leads to me to believe that you need to review ROS parameters and launch files.

This board is for reporting bugs and feature requests, and what you're reporting don't really fit, but are questions that can be answered by the community.

**Comment by DaDaDoDoLee** [comment]
OK，I'll go through the relevant ROS tuitorials.Thank you Tom
