### ISSUE TITLE
Cannot build on Ubuntu mate - RaspberryPi 3

### ISSUE THREAD

**Issue by BetterRobotics** [cra-ros-pkg/robot_localization#369]
NEVER SUBMITTED A BUG BEFORE!! 

I installed this package on my RPI3 with ubuntu mate 16.04, it seems to be hanging when running the catkin_make command, it builds up to the ros_fitler.cpp however it just sits there.  When pressing crtl+c it responds like it's stuck in a while loop which blocking the interrupt key command and takes a long time to register, any idea what the problem is? or where to look for a fix? 

Cheers Ben.

**Comment by ayrton04** [comment]
Er, that sounds a bit like a compiler issue. I don't have a Raspberry Pi, so it's hard for me to replicate, but I have built the package successfully on ARM boards before. Can you use catkin_tools instead and run `catkin build`?

**Comment by tonybaltovski** [comment]
Are you running out of RAM and swap?  I had the same issue on my Raspberry Pi 2 when compiling.

**Comment by BetterRobotics** [comment]
I am not sure how to check that, but the PI3 has 1G of RAM so I wouldn't think so. It was like the makefile was waiting for something to build before it would move on (maybe a dependency problem), each time I killed it I saw something like " pr.wait_for() " in some of the error output but couldn't really make sense of it.

Cheers Ben.

**Comment by tonybaltovski** [comment]
Run `top` while compiling and watch the amount of memory and swap that is free.

**Comment by caseypen** [comment]
Hi All,
Are there any updates about this issue? I met the same problem with Cheers and it stopped at the compiling process "Building CXX object robot_Localization/CMakeFiles/ros_robot_localization_listener.dir/src/ros_robot_localization_listener.cpp.o". I checked top and it runs out of memory while doing compiling. 
Chen Peng

**Comment by ayrton04** [comment]
I don't have any of the boards in question in my possession, I'm afraid, so I can't replicate the issue. Can you try cloning and old version of the software from one of the release tags and building that? It would at least help to isolate when this became an issue. It's interesting that these build issues appear to be isolated to certain compilers.

**Comment by tonybaltovski** [comment]
@caseypen do you have swap on your Raspberry Pi 3? And if so, how much do you have?

**Comment by caseypen** [comment]
Hi All,
Thanks for replying. @tonybaltovski the swap size is set as default, it should be 100M. 
The compiling of latest version is finished by several times of breaking and restarting. It can work now.
Thanks!
Chen

**Comment by ayrton04** [comment]
Can this be closed?

**Comment by BetterRobotics** [comment]
Hi Tom,

I still feel the problem could be rectified for ARM based projects but, I was unable to determine if it was indeed the swap running out due to time constraints. It would be nice if it was able to build on the ARM processor! But unfortunately I am unable to assist with correcting the issue however I can help with testing.

On 8 Dec 2017, at 2:58 am, Tom Moore <notifications@github.com<mailto:notifications@github.com>> wrote:


Can this be closed?

**Comment by caseypen** [comment]
Hi Tom,
Thanks for your help and replying. Actually I finishing compiling on
Raspberry Pi though with several times of out of memory error. But I think
it should work fine on other ARM based board with better configuration.
Best

Chen

**Comment by ayrton04** [comment]
Have you tried compiling with `catkin build -j1`? I am going to close, but if anyone has time/interest, feel free to reopen.

**Comment by BetterRobotics** [comment]
Hi Tom,

As Chen mention it was in fact a memory error the pi is running out of memory before it can complete the entire build! Chen’s method of restart/build didn’t work for me. Unsure to why!

I have tried -j1 command but this didn’t not work as it’s not an over processing issue! It’s memory! From memory (going back a bit) I always failed at about 70% from a “fresh build” but never had success to actually build a working package! I was using Ubuntu mate 16.04 on pi3.

Don’t think this should be closed as you need more people to provide testing! I might be able to help out in the next few weeks but need to know exactly what you need for debug to get rid of the ninja bugs! ☺️

On 19 Jun 2018, at 10:00 pm, Tom Moore <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you tried compiling with catkin build -j1? I am going to close, but if anyone has time/interest, feel free to reopen.

**Comment by ayrton04** [comment]
Yes, understood that it's a memory issue, but `-j1` forces a single thread, and so if we were compiling two or more source files at the same time before, compiling one should use less memory. Regardless, I can keep this open.

**Comment by BetterRobotics** [comment]
Agreed, I feel the the -j1 option might have lead to Chan’s success but cannot stipulate any further, being a single thread means that when it runs out of SWAP memory the compiler and locks up the logging feature has a greater chance of actually resuming the build process in at the correct location. I will have a bit of time over the next few weeks to test it out. I’m not super linux orientated but can follow instruction to nail the issue if your interest to resolve this.

Cheers Ben




On 19 Jun 2018, at 10:52 pm, Tom Moore <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, understood that it's a memory issue, but -j1 forces a single thread, and so if we were compiling two or more source files at the same time before, compiling one should use less. Regardless, I can keep this open.

**Comment by subodh-malgonde** [comment]
`catkin_make -j1` worked for me. It took a long time for the code to build though.

**Comment by tomsepe** [comment]
I also ran into this issue today. Where catkin_make just hung.

Trying the catkin_make -j1 option and so far it seems to be working.... I got based the hang point (see below) and is now building fine, although slowly :)

<img width="744" alt="Screen Shot 2019-03-28 at 8 39 57 AM" src="https://user-images.githubusercontent.com/1732025/55172056-ac299180-5136-11e9-88a8-7ee6c30618fc.png">

**Comment by SteveMacenski** [comment]
I built this on my jetson nano over the weekend without a problem (A57 cores) with my catkin config. I'm inclined to say this ticket should be closed since its just requiring swap.

**Comment by BetterRobotics** [comment]
Yes close ticket, just swap issue no issues with actual build 👌🏼 thanks all
👌🏼

Sent from my iPhone

On 5 Dec 2019, at 7:56 am, Steven Macenski <notifications@github.com<mailto:notifications@github.com>> wrote:


I built this on my jetson nano over the weekend without a problem (A57 cores) with my catkin config. I'm inclined to say this ticket should be closed since its just requiring swap.
