### ISSUE TITLE
Use of pose from a unique odometry message in both ekf_se_odom and ekd_se_map

### ISSUE THREAD

**Issue by Yvonnn** [cra-ros-pkg/robot_localization#371]
Hello,

I am fusing odometry from a lidar (I have it thanks to undocumented pub_odometry parameter of hector_slam), IMU and GPS data. I am using the dual_ekf_navsat_example.
My odom message has no twist information, only pose. So that it is taken into account by ekf_se_odom, I need to publish it with frame_id = odom, because world_map of ekf_se_odom is odom.
Then, if I want my odom message to be fused again in ekf_se_map, I need to publish it with frame_id = map, because world_map of ekf_se_map is map.
So... I guess I have to duplicate my odom message... am I right or am I missing something ?

Yvon

**Comment by ayrton04** [comment]
Did you ask this on answers.ros.org? If so, can you please point me to it?

**Comment by Yvonnn** [comment]
Sorry about that. It is done here now : http://answers.ros.org/question/265007/what-is-good-practice-to-fuse-pose-from-a-unique-odom-message-in-robot_localization-in-both-ekf_se_odom-and-ekf_se_map/?comment=265077#post-id-265077

**Comment by ayrton04** [comment]
Closing (question answered).
