### ISSUE TITLE
Link to docs on ROS wiki

### ISSUE THREAD

**Issue by anthonyjclark** [cra-ros-pkg/robot_localization#373]
I'm not sure which repository this issue belongs to. 

On http://wiki.ros.org/robot_localization the **Lunar** tab does not link to the [documentation](http://docs.ros.org/kinetic/api/robot_localization/html/index.html), but the **Kinetic** tab does.

**Comment by ayrton04** [comment]
Thanks for the heads-up. Fixed now.
