### ISSUE TITLE
RGB_D SLAM and IMU

### ISSUE THREAD

**Issue by yalan2017** [cra-ros-pkg/robot_localization#380]
Hi
I am using [Rtabmap ](wiki.ros.org/rtabmap)and IMU in order to fuse my map with robot localization package but i have error and i try different way to solve but i could solve my problem. this is my [launch ](https://github.com/introlab/rtabmap_ros/blob/master/launch/tests/sensor_fusion.launch)file .
and we discussed before here [ 1 ](http://official-rtab-map-forum.67519.x6.nabble.com/tinkerforge-imu-td1886.html#a3690) [2!](http://official-rtab-map-forum.67519.x6.nabble.com/tinkerforge-imu-td1886i20.html) .
 this is my topic list 
![screenshot from 2017-10-13 21 06 58](https://user-images.githubusercontent.com/25242807/31547637-b28f4fc0-b05a-11e7-9154-f4f0c4073655.png)

my  result:
![screenshot from 2017-10-13 19 31 05](https://user-images.githubusercontent.com/25242807/31547676-d322fd9a-b05a-11e7-86ad-eae57b614601.png)
my frames:
![frames](https://user-images.githubusercontent.com/25242807/31547744-08c3d73a-b05b-11e7-91bc-88ee999b0087.png)

Thank you 

 @jspricke 
@efernandez 
@mitchellwills

**Comment by ayrton04** [comment]
Hi! This board is for reporting bugs. Please direct questions to answers.ros.org. If you have already asked a question there, can you please direct me to it?

**Comment by yalan2017** [comment]
hi
im sorry for that, i have written my problem here :  
https://answers.ros.org/question/261724/robot_localization-imu-and-visual-odometry-from-rtabmap/?answer=273047#post-id-273047
@ayrton04 
thank you
