### ISSUE TITLE
Is there any clean package that allows integration of LIDAR / SLAM information to be fed into the Localization Stack?

### ISSUE THREAD

**Issue by candersen10** [cra-ros-pkg/robot_localization#385]
Hello,

Is there any clean package that allows integration of LIDAR / SLAM information to be fed into the Localization Stack (in addition to GPS, IMU, Odometry)?  We are trying to do navigation with a breadcrumb style approach outside of the navigation stack in an outdoor environment, hence the question.

Thanks

**Comment by ayrton04** [comment]
This board is really for reporting issues with the `robot_localization` package. If you have questions, would you mind posting them at [answers.ros.org](answers.ros.org)?
