### ISSUE TITLE
MahalanobisThresh parameter typo for IMU

### ISSUE THREAD

**Issue by pavloblindnology** [cra-ros-pkg/robot_localization#387]
`twistMahalanobisThresh` should be instead of `poseMahalanobisThresh`.
https://github.com/cra-ros-pkg/robot_localization/blob/b086199c360ca00deba620a18899313aa8224463/src/ros_filter.cpp#L1338

**Comment by ayrton04** [comment]
Thanks for pointing out the bug. Care to submit a PR?

**Comment by pavloblindnology** [comment]
Ok

**Comment by ayrton04** [comment]
Thanks!
