### ISSUE TITLE
Invalid generated cmake config files

### ISSUE THREAD

**Issue by tfoote** [cra-ros-pkg/robot_localization#392]
The latest release [2.4.1 on Kinetic](https://github.com/ros/rosdistro/pull/16599) is generating invalid CMake Config files.

Refiling: https://github.com/clearpathrobotics/cpr_multimaster_tools/issues/2

The first failed build was triggered by the release of robot_localization: http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__message_relay__ubuntu_xenial_amd64__binary/30/
![image](https://user-images.githubusercontent.com/447804/34276096-bdf1da6a-e654-11e7-85dd-6a21f02860d7.png)

**Comment by ayrton04** [comment]
Whoops. Not sure what's up there. Will investigate.

**Comment by ayrton04** [comment]
Not entirely sure what happened, but I tried re-blooming, and bloom wasn't happy when applying a patch to rules.em. I've got it back to a happy state, so we'll see how it behaves downstream. If it still gives us trouble, I'll roll it back and deal with it later.

**Comment by tfoote** [comment]
Thanks for the quick turn @ayrton04 !
Cross reference: https://github.com/ros/rosdistro/pull/16636

**Comment by ayrton04** [comment]
Not convinced it helped. Rolling back to 2.4.0.

**Comment by tfoote** [comment]
Yeah, it looks like the rebuild failed: http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__message_relay__ubuntu_xenial_amd64__binary/36/console

**Comment by ayrton04** [comment]
Yeah, I'm rolling it back: https://github.com/ros/rosdistro/pull/16638

Odd that it has a bunch of downstream projects, but only a [couple of them](http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__robot_localization__ubuntu_xenial_amd64__binary/) are failing.

If the rollback still fails, I'll pick it back up in the AM. Sorry for the trouble!

**Comment by kenautics** [comment]
Rollback fixed it. I’ll investigate what broke and release again after the kinetic sync. Thanks for pointing it out!

**Comment by ayrton04** [comment]
Rollback fixed it. I’ll investigate what broke and release again after the kinetic sync. Thanks for pointing it out!

**Comment by ayrton04** [comment]
Update: I ran a prerelease on this with a dependency level of 1, and was able to re-create the issue. We had a PR submission for some new libraries and a new node, but it wasn't installing said objects. I've fixed it and am running a prerelease test again. If that succeeds, I'll bloom.

Sorry for the trouble!
