### ISSUE TITLE
robot_location  ekf_localization_node

### ISSUE THREAD

**Issue by laixinzuan** [cra-ros-pkg/robot_localization#395]
Hi all,
   I'm working on fusing odom(x,y,yaw) and imu(yaw) for robot localization purpose.The robot worked well when it was started, but then the robot drifted. I try to push the robot movement, the robot will deviate from the track. Is this related to the setting of process_noise_covariance? imu、odometry's noise_covariance is set  separately in robot_pose_ekf, , but  imu、odometry's noise_covariance is set  process_noise_covariance in robot_location. I wonder if robot drift is related to covariance? Who can help me? thank you!
ekf_se_odom:
  frequency: 30
  sensor_timeout: 0.1
  two_d_mode: true
  transform_time_offset: 0.0
  transform_timeout: 0.0
  print_diagnostics: false
  debug: false

  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

  odom0: odometry/wheel
  odom0_config: [true,  true,   false,
                 false, false,  true,
                 true,  false,  false,
                 false, false,  false,
                 false, false,  false]
  odom0_queue_size: 10
  odom0_nodelay: true
  odom0_differential: false
  odom0_relative: false

  imu0: imu/data
  imu0_config: [false, false, false,
                false, false, true,
                false, false, false,
                false, false, false,
                false, false, false]
  imu0_nodelay: false
  imu0_differential: false
  imu0_relative: false
  imu0_queue_size: 10
  imu0_remove_gravitational_acceleration: true
  use_control: false

**Comment by ayrton04** [comment]
This board is really meant for reporting bugs and requesting features. Please ask questions on answers.ros.org. When you do, please include your EKF config, as well as a sample message from every sensor input that you have.
