### ISSUE TITLE
nav_sat_transform tf from utm to odom time wrong

### ISSUE THREAD

**Issue by sean85914** [cra-ros-pkg/robot_localization#408]
I used nav_sat_transform to publish tf from utm to my odom frame "odom", but when I typed
$ rosrun tf tf_view /utm /odom 
I always got the result like following
"""
At time 0.000
- Translation: [301576.529, 2719291.612, 0.000]
- Rotation: in Quaternion [0.000, 0.000, 0.556, 0.831]
            in RPY (radian) [0.000, -0.000, 1.180]
            in RPY (degree) [0.000, -0.000, 67.597]
"""
which the time is wrong.
So when I call lookupTransform('/utm','/odom', rospy.Time(0)), I couldn't get the result transformation
My config file for nav_sat_transform is as following
[https://github.com/seanNCTU/rv_2018_project/blob/master/catkin_ws/src/robot_localization/params/rv_gps.yaml](url)

How can I solve this problem?
Best regard

**Comment by ayrton04** [comment]
Thanks for the question. However, I would ask that you please ask all questions on answers.ros.org.
