### ISSUE TITLE
Preparing the IMU for ENU coordinate frame

### ISSUE THREAD

**Issue by supermaro84** [cra-ros-pkg/robot_localization#410]
Hello,
I have a vectornav 200 IMU for which i am using the driver provided here:
https://github.com/dawonn/vectornav

I wasn't able to find a clear answer on how to prepare the IMU to be used in EKF node.
Apparently the IMU is publishing its orientation in NED frame. In case I would like to use the IMU with no translation and rotation wrt base_link,
1. How should the actual device be placed? 
2. What should be the static transform wrt base_link?
3. How to make imu publish in ENU frame?

I have used the setup proposed here: 
https://github.com/ros-perception/imu_pipeline/blob/indigo-devel/imu_transformer/launch/ned_to_enu.launch
 but so far I wasnt able to get the right result.
Thanks!

**Comment by ayrton04** [comment]
Thanks for the question. However, I would ask that you please ask questions on answers.ros.org. Thanks!
