### ISSUE TITLE
IMU wrong Z estimation

### ISSUE THREAD

**Issue by caiofis** [cra-ros-pkg/robot_localization#413]
I have noticed a wrong Z estimation when fuse my wheel or visual odometry with an IMU. The overall shape of the trajectory seems pretty good, but mirrored in the Z axis. This way when the robot goes up a hill in the estimation is seems like a down hill.
I am only fusing the angular velocity from the IMU, since my linear acceleration seems too noisy. Is it related with the ambiguity between NED/ENU frames? 
Did you ever face the same problem @ayrton04 ?

**Comment by ayrton04** [comment]
Thanks for the question. However, we ask that all questions be posted on answers.ros.org.
