### ISSUE TITLE
navasat_transform_node: GPS sensor requirments 

### ISSUE THREAD

**Issue by peterpanda01** [cra-ros-pkg/robot_localization#423]
I've successfully developed my ekf_localization_node to publish /odometry/filtered; i have a sensors publishing /imu/data and /gps/fix. However when i try to feed this data to the navsat_transform_node it doesn't publish anything to the /odometry/gps topic? Do i have to have a second ekf_node that configures the topic to an odom sensor? Do i need to have a certain amount of covariance in the /gps/fix topic? Do i just have the wrong GPS Sensor; i use an [adafruit ultimate gps](https://learn.adafruit.com/adafruit-shield-compatibility/ultimate-gps-shield) with the nmea_navsat_driver [ROS package](http://wiki.ros.org/nmea_navsat_driver).

**Comment by ayrton04** [comment]
Hi, and thanks for the question. However, I ask that all questions be asked on answers.ros.org. If you already have, can you please point me to it? Thanks.
