### ISSUE TITLE
how to understand differential mode and relative mode?

### ISSUE THREAD

**Issue by ScottYu779** [cra-ros-pkg/robot_localization#429]
in the yaml file,the follow tow parameters :imu0_differential: false  imu0_relative: false will be parsed to be two mode variables,but when i reading the src,i found the two mode is hard to understande,please help me!

**Comment by ayrton04** [comment]
Thanks for the question. However, I ask that all questions be directed to answers.ros.org. If you already asked it there, can you direct me to it? Thanks.
