### ISSUE TITLE
Document undocumented parameters

### ISSUE THREAD

**Issue by maracuya-robotics** [cra-ros-pkg/robot_localization#441]
Some parameters like `predict_to_current_time` (and maybe more?) are not documented.

**Comment by ayrton04** [comment]
Thanks for the report. I'd welcome a PR!

**Comment by maracuya-robotics** [comment]
Wow, that was fast!

Found another one, `disabled_at_startup`. IMHO documentation should be done by someone who knows what these parameters do. I can just guess by the name and by looking at the code.

**Comment by diasdm** [comment]
I think these are all the undocumented parameters for the documented nodes.

In `navsat_transform.rst` is missing:
* transform_timeout (only documented for `state_estimation_nodes.rst`)

In `state_estimation_nodes.rst` is missing:
* base_link_frame_output
* predict_to_current_time
* disabled_at_startup

**Comment by seebq** [comment]
Hey @maracuya-robotics and @diasdm I submitted a PR #454 for y'all.  Can you review and let @ayrton04 know if this documents the parameters that were missing?

**Comment by ayrton04** [comment]
Assuming this is addressed by #454. Thanks @seebq.
