### ISSUE TITLE
How to state start position (x,y,z,r,p,y) for ekf.

### ISSUE THREAD

**Issue by Sollimann** [cra-ros-pkg/robot_localization#448]
Im using UUV_simulator combined with your robot_localization package. I have been successfully been able to implement ekf with DVL, IMU and Pressure Sensor. The odometry estimate all start at (x,y,z,r,p,y) = (0,0,0,0,0,0), but I would like to start the node at my launch position in Gazebo simulator. How can I do this? I want my robot to launch at position (15,-20,0, 0,0,0) so that the ekf estimate proper pose interms of gazebo world frame.

**Comment by ayrton04** [comment]
Thanks for the question. However, all questions should be directed to answers.ros.org, and I will respond to it as time allows. Thanks!
