### ISSUE TITLE
tf2  issue with lidar odometry integration

### ISSUE THREAD

**Issue by brunoeducsantos** [cra-ros-pkg/robot_localization#450]
Hi,
Running both robot_localization package and the slam ros package that generates lidar odometry, the following error comes up:

  

>   at line 134 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp
> Warning: Invalid argument "/camera" passed to canTransform argument source_frame in tf2 frame_ids cannot start with a '/' like:
>          at line 134 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp
> Warning: Invalid argument "/camera_init" passed to canTransform argument source_frame in tf2 frame_ids cannot start with a '/' like:
>          at line 134 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp
> Warning: Invalid argument "/camera" passed to canTransform argument source_frame in tf2 frame_ids cannot start with a '/' like:
>          at line 134 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp
> Warning: Invalid argument "/camera_init" passed to canTransform argument source_frame in tf2 frame_ids cannot start with a '/' like:
>          at line 134 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp
> Warning: Invalid argument "/camera" passed to canTransform argument source_frame in tf2 frame_ids cannot start with a '/' like:
>          at line 134 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp
> 

My tf tree is the following:
![rosgraph](https://user-images.githubusercontent.com/3111976/53488831-586c4f80-3a87-11e9-8f95-24d7fcdcb5bd.png)

 
Can anyone help me?
Thanks,
Bruno

**Comment by brunoeducsantos** [comment]
I just need to remove the slash in SLAM ros package.

**Comment by ayrton04** [comment]
Yeah, `tf2` doesn't support leading slashes. If you have further questions/issues, answers.ros.org is a great resource.
