### ISSUE TITLE
Can I use robot_loc for ackerman steering

### ISSUE THREAD

**Issue by CesMak** [cra-ros-pkg/robot_localization#452]
Hey there,

I shortly wanted to ask if I also can use this package for an ackermann steering robot or is this package just related to work for differential drive. 

Or is it as I assume more general and I simply have to feed in the sensor data correctly no matter if I have ackermann steering or a uav / quadrotor etc.

Thanks :)

**Comment by ayrton04** [comment]
Hi and sorry for the delay. Can you please ask this on answers.ros.org? If you already have, can you please direct me to the question? Thanks.
