### ISSUE TITLE
2d  on the wall (gravity is on the same plane with x and y axis)

### ISSUE THREAD

**Issue by GITSHOHOKU** [cra-ros-pkg/robot_localization#455]
Hi! Thanks for providing this package
I just start use this package on a climbing robot on the wall(with imu and wheel odom). Can I  just use  2d  mode  the estimate robot position and velocity on the wall. Did the gravity co-planar with x and y axis effect the estimation?

**Comment by GITSHOHOKU** [comment]
Can the 2d mode compensate the gravity even it co-planar with x-y axis?

**Comment by ayrton04** [comment]
Thanks for the question. However, we ask that all questions be directed to answers.ros.org.
