### ISSUE TITLE
tf_prefix not added to base_link

### ISSUE THREAD

**Issue by faizansid77** [cra-ros-pkg/robot_localization#464]
The node is running perfectly when I am not using any tf_prefix. Whenever I use tf_prefix, I get no tf_prefix in base_link. This issue is not observed in version 2.4.5. Please revert the code to whatever changes you made after 2.4.5

My /robot1/odom/filtered is publishing this  header:
`header: 
  seq: 181
  stamp: 
    secs: 627
    nsecs: 240000000
  frame_id: "robot1_tf/odom"
child_frame_id: "base_link"
`

My robot's namespace is "robot1" and tf_prefix is "robot1_tf" 

Edit: I am working on ros-kinetic

**Comment by ayrton04** [comment]
Yep, that's a bug. Try this branch:

https://github.com/cra-ros-pkg/robot_localization/tree/fix-output-tf-prefix
