### ISSUE TITLE
use navsat_transform utm2map_TF to navigate 

### ISSUE THREAD

**Issue by pzy2253999075** [cra-ros-pkg/robot_localization#466]
I want to use navsat_transform to locate my  robot in utm frame for navigation. But the utm2map_TF is just published once when launching  navsat_transform_node.I think it can't  be updated as robot is moving.So I want to know wheather navsat_transform_node is suitable for locating robot in utm frame in real time?Could someone tell me that, thank.

**Comment by ayrton04** [comment]
Thanks for the question. However, we ask that all questions be asked on answers.ros.org.
