### ISSUE TITLE
syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by ghost** [cra-ros-pkg/robot_localization#468]
I have downloaded the package and also did the catkin_make. I also made the test launch file executable.But when I am running it getting this following error.Can anyone please tell me how to resolve this issue?

/home/nvidia/myworkspace/src/robot_localization/test/test_ukf_localization_node_bag1.test: line 1: syntax error near unexpected token `newline'
/home/nvidia/myworkspace/src/robot_localization/test/test_ukf_localization_node_bag1.test: line 1: `'

Thanks

**Comment by ayrton04** [comment]
Would you mind asking this on answers.ros.org? Thanks.
