### ISSUE TITLE
Drppng gps navsat transform connection

### ISSUE THREAD

**Issue by Ashik19** [cra-ros-pkg/robot_localization#474]
Can anyone please help me with this issue ?When I am trying to use the /gps/odometry topic I am getting the following error. I have an inertial sense sensor which gives /gps, /imu, /ins data. I am trying to use all this 3 topics in the /gps/odometry topic but coming up with the following error. 

![Screenshot from 2019-07-16 04-35-19](https://user-images.githubusercontent.com/52055757/61288058-92fb2e00-a783-11e9-89e0-3bfa83811d34.png)

Thanks.

**Comment by ayrton04** [comment]
Thanks for the question. However, we ask that all questions be asked on answers.ros.org. I can tell you right now that you are using the wrong message type. As the error states, the message type `navsat_transform_node` wants is `NavSatFix`, and you are giving it a `inertial_sense/GPS`.
