### ISSUE TITLE
Where is the https://www.cra.com/robot_localization_ias13.zip

### ISSUE THREAD

**Issue by JuneJulyAugust** [cra-ros-pkg/robot_localization#479]
It seems that cra had deleted the link. Does anyone have the bag?

**Comment by ayrton04** [comment]
Sadly, I don't anymore. I have scoured my backups for it, and it's just nowhere to be found. Not sure why CRA deleted it, or if they have a copy somewhere.

If anyone else downloaded it at some point and still has it, that would be great.

**Comment by SteveMacenski** [comment]
Lost to time, closing
