### ISSUE TITLE
IMU Centripetal force

### ISSUE THREAD

**Issue by sts-hmm** [cra-ros-pkg/robot_localization#494]
## Bug report

**Required Info:**

- Operating System: Ubuntu 16.04, ROS Kinetic
- Installation type: from source
- Version or commit hash:
  -kinetic-devel branch 2.48: 4317f16931a4691625874a0684614b8de0afd8be

#### Steps to reproduce issue
I am using the robot_localisation with a RTK GPS (2cm accuracy) and an IMU in an ackermann vehicle. The GPS has an update rate of 2Hz, the IMU has an update rate of 50Hz. To get a continuous pose output, I tried to fuse both sensors. This seems to work for slow velocities, but when driving a circle with higher velocities I get a "sawtooth" behaviour, where the output is drifting towards the center of the circle until the next GPS message is received and the output jumps back to the correct path.

I tried to analyse the behaviour and wrote a simulation node to output correct and error free data for testing and noticed that high lateral acceleration is triggering this behaviour. For testing, I set the lateral acceleration to zero in my simulation node and this behaviour is gone (output is fine).

My assumption is, that the robot_localisation does not take centripetal forces into account. Is this right? Is it possible to enable this feature?
(I tried to set the lateral accelerations to "false" in the imu_config matrix, but the error still exists. Only after setting the lateral acceleration sensor output to zero, the drift behaviour is gone. This seems strange to me, because the data is still used, even if I put the config to false?)

**Comment by ayrton04** [comment]
Please ask this question on answers.ros.org. After discussion there, if we find that it is indeed a bug (this sounds, if anything, like a feature request), we can re-open this. If you've already asked the question there, please post a link here, and then I would ask for your patience. I don't get a lot of time to dedicate to this package from day to day.
