### ISSUE TITLE
Strange estimator behavior

### ISSUE THREAD

**Issue by mohradza** [cra-ros-pkg/robot_localization#500]
Ubuntu 18.04.3 LTS. Forked the most recent version of the master branch on GitHub.

I am seeing some strange estimator behavior where the estimator seems to be stuck in a predict cycle for several seconds, even though it appears the sensor measurements are coming in consistently. 

Some more background: We are trying to generate odometry estimates from a single IMU and two "velocity sensors". These "velocity sensors" provide measurements of linear velocity in the body frame. During our initial testing, we were able to generate pretty accurate odometry estimates, over the course of a 120m walk with our sensor rig. Since original testing, we have moved all the sensors to a new vehicle. The biggest difference between the rig and the vehicle is the placement of the sensors, however we have adjusted the sensorX->base_link transforms to reflect their new locations. With the new setup, we keep getting the same results, which look like this:

![VelPlot](https://user-images.githubusercontent.com/22601768/68326934-9e9f9700-0089-11ea-9ebe-470ef854d807.jpg)

This is a plot of the measured velocities vs the estimated velocity, where the measured velocities are shown in blue and green and the estimate in red. One can see that up to approximately the 10 second mark, the estimator is tracking appropriately. Then it just stops and has a seemingly linear slope. The position plots show the inconsistencies as well:

![PosPlot](https://user-images.githubusercontent.com/22601768/68327158-0ce45980-008a-11ea-861e-03f68702ba2a.jpg)

For completeness, here are the linear acceleration measurements coming from the imu:
![LinAccelPlot](https://user-images.githubusercontent.com/22601768/68327289-474df680-008a-11ea-9cd9-a87516085f95.jpg)

So far we have tried making several changes. Changing the timeout frequency for the sensors did not have any effect. We have reduced the number of sensors down to a single velocity sensor, and the results are the same. We have tried changing the data rates of the sensors, which did not have any effect either. The issue seems to be related to specific motions. Here are the velocity plots from a different dataset, where the vehicle motions are the same as previous datasets:

![VelPlot2](https://user-images.githubusercontent.com/22601768/68327617-e541c100-008a-11ea-8004-766148058db2.jpg)

If anyone has any insight as to what might be causing this behavior and what I need to do to fix it, please let me know! I can provide bagfiles for these datasets and the associated launch files if that would help debugging efforts.

Cheers!

Here is the params file. Note, the imu config should have the linear accel measurements set to true.

[A01_ekf.zip](https://github.com/cra-ros-pkg/robot_localization/files/3816202/A01_ekf.zip)

**Comment by mohradza** [comment]
I am not sure if this is a bug necessarily, but I cannot figure out how to change the tag.

**Comment by mohradza** [comment]
This appears to be a result of the rejection threshold being applied to the velocity measurements. After commenting out the thresholds, these blips in the estimates no longer exist.

**Comment by ayrton04** [comment]
In the future, I'd recommend asking questions on answers.ros.org before submitting tickets. If you already did that, I apologise. I'm having a hard time answering questions in a timely fashion.
