### ISSUE TITLE
parameter problem

### ISSUE THREAD

**Issue by Fanny-one** [cra-ros-pkg/robot_localization#503]
Hi， I have used robot_localization in my project. In my urdf my rpy of imu is {0 0 -1.6301} as  show in the graph.
![微信图片_20191115192453](https://user-images.githubusercontent.com/52403161/69023179-d3e8a500-09f8-11ea-8098-3067ffa97aa1.jpg)
Besides, the yaw is from dual-antenna direction not magnetometer so I needn't magnetic_declination_ . According to api I set offset 1.57. When I use SLAM and localization simultaneously, they always match badly. I think my slam is unproblematic and the parameter of localization is improper probably. I don't know why.

![bc80bb097b425f51c8e2d57c2c37a03](https://user-images.githubusercontent.com/52403161/69023078-794f4900-09f8-11ea-8f57-6bd470cf32f7.jpg)

Now I hope your help, wait for your reponse.

**Comment by ayrton04** [comment]
Hi,

Thanks for the question. However, we ask that all questions be directed to answers.ros.org. If you've already asked this there, please provide the link. Thanks.

**Comment by Fanny-one** [comment]
@ayrton04  
https://answers.ros.org/question/337930/robot_localization-parameter/
Thanks very much!
