### ISSUE TITLE
what 6-dof kinematics model is applied here?

### ISSUE THREAD

**Issue by NILIWEI** [cra-ros-pkg/robot_localization#506]
## Feature request
For 6DOF kinematics model here,where this way to calculate the state equation param in predict process?

**Comment by ayrton04** [comment]
Is this a question, or a feature request? If it's a question, can you please ask it on answers.ros.org? Also, I'm not quite clear on what it is you're asking. Do you just want to know where the kinematic model lives, and what kind it is?
