### ISSUE TITLE
Thread safety for measurementQueue_

### ISSUE THREAD

**Issue by zhangjian-neu** [cra-ros-pkg/robot_localization#507]
Dear authors,

Recently, I studied the package robot_localization. I find the variable 'measurementQueue_' can be updated in different callback functions, when new measurement ROS topic comes. 

As I know, the "topic-callback" mechanism is concurrent. This means the variable 'measurementQueue_' may be **concurrently** updated, when multiple measurement ROS topics come. 

Without extra thread safety mechanism , currently modifying the variable 'measurementQueue_' is not safe.  I hope to inquire where this issue is dealt with in the source codes, or whether this issue will be improved in future work.

Really thanks for your effort! 

I am looking forward to hearing from you.

**Comment by ayrton04** [comment]
> As I know, the "topic-callback" mechanism is concurrent

No, this is not accurate. The callback queue is single threaded, and callbacks are fired sequentially. See [this](http://wiki.ros.org/roscpp/Overview/Callbacks%20and%20Spinning) wiki for more information.

**Comment by zhangjian-neu** [comment]
Great! Sincerely thanks for your kindly reply.
