### ISSUE TITLE
What it according to calculate controlAcceleration_?

### ISSUE THREAD

**Issue by NILIWEI** [cra-ros-pkg/robot_localization#513]
In ekf.cpp/predict function,why this way to calculate controlAcceleration_ , and what it according to?
And about x  =f(x,u) , 
in your project is x += u ,then do x = transferFunction_ * x,
if it mean that x = transferFunction_*(x + u) ---> x = transferFunction_*x + transferFunction_*u? 
**So you just predict the u as the same as x**?
Thanks ahead!

**Comment by ayrton04** [comment]
Please direct all questions to answers.ros.org. If you have asked the question there already, please provide a link to it, and I'll get to it when I can. Thanks.
