### ISSUE TITLE
How to run with LOAM_velodyne and IMU

### ISSUE THREAD

**Issue by ROSnew** [cra-ros-pkg/robot_localization#515]
Hello.
I try to run it on data. For example, on KITTI dataset. LOAM (https://github.com/laboshinl/loam_velodyne) gives odometry with frame_id = 'camera_init' and child_frame_id = 'camera'.
I know transform between LIDAR and IMU.
And as i understood, i should set parameters

**publish_tf**: false
 **odom_frame**: camera_init
 **base_link_frame**: camera
 **world_frame**: camera_init 
Which transform i forgot?
 
![screen](https://user-images.githubusercontent.com/59201211/71446597-2161db80-2736-11ea-9219-85a37182d725.png)
[KITTI.launch.txt](https://github.com/cra-ros-pkg/robot_localization/files/4000508/KITTI.launch.txt)
[KITTI.yaml.txt](https://github.com/cra-ros-pkg/robot_localization/files/4000511/KITTI.yaml.txt)

**Comment by SteveMacenski** [comment]
@ROSnew please open a ticket on ROS Answers for configuration assistance.
