### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by AlexisTM** [cra-ros-pkg/robot_localization#517]
## Bug report

**Required Info:**
- Operating System:
  - Ubuntu 18.04
- Installation type:
  - Source
- Version or commit hash:
  - 6956176041630361364c06f554e319988e251300

#### Problem

In multiple places, there are new pointers created to be able to call the same functions as the callback functions yet I cannot find any `delete`.

https://github.com/cra-ros-pkg/robot_localization/blob/6956176041630361364c06f554e319988e251300/src/ros_filter.cpp#L505-L524

This is done to fit ROS callback implementation where data freeing is handled by the spinner.

https://github.com/cra-ros-pkg/robot_localization/blob/6956176041630361364c06f554e319988e251300/src/ros_filter.cpp#L1749-L1752

**Comment by ayrton04** [comment]
Line 523 above shows this:

```
geometry_msgs::PoseWithCovarianceStampedConstPtr pptr(posPtr); 
```

`geometry_msgs::PoseWithCovarianceStampedConstPtr` is really a `boost` `shared_ptr`. When you pass a raw pointer to a shared pointer in the constructor, it takes over management of the raw pointer.

From the [documentation](https://www.boost.org/doc/libs/1_63_0/libs/smart_ptr/shared_ptr.htm):

> The shared_ptr class template stores a pointer to a dynamically allocated object, typically with a C++ new-expression. The object pointed to is guaranteed to be deleted when the last shared_ptr pointing to it is destroyed or reset.

> Example:
shared_ptr<X> p1( new X );
shared_ptr<void> p2( new int(5) );

In any case, this package is being used on thousands of robots in production environments. Our robots might run for months between restarts. If there were a per-measurement memory leak, I think there would be a lot of complaints by now. If you are actually seeing the node leak using some kind of instrumentation, though, let me know.
