### ISSUE TITLE
Different input sampling rates & acceleration in motion model

### ISSUE THREAD

**Issue by Fugashu** [cra-ros-pkg/robot_localization#540]
Hello,

we are currently fusing IMU, Wheel Odometry and Visual Odometry data with your robot_localization package. Since we have different sampling rates (eg. we receive 100 IMU messages and 1 VO message in the same time window) the question arised whether this problem is handled within the package or not.

Furthermore we took at look at the motion model you are using. We ask ourselves why the X and Y -Velocities are simply calculated by multiplying the X/Y acceleration times the delta without influence of any angle.

Thanks for your time.

**Comment by SteveMacenski** [comment]
Hi,

Please direct questions to ROS Answers, but I believe your questions are addressed in the documentation. If you still have questions after reading them, please ask on ROS answers.
