### ISSUE TITLE
Static drift at initial position

### ISSUE THREAD

**Issue by linzha0** [cra-ros-pkg/robot_localization#546]
I am using a rosbag inclusing: gps data, filtered imu(using imu_filter_madgwick), imu raw data, DVL data(measure vehicle velocity), gps ekf odometry(the ground truth). I am trying to fuse imu-DVL offline to compare the gps ekf odometry.

![entire_drift](https://user-images.githubusercontent.com/11235093/77128260-d77f4d80-6a25-11ea-979f-03bf98c4905b.png)
**Figure 1: gps fused path and filtered imu fused path**

In Figure 1, the green is the gps-fused path. white is the imu-filtered and DVL fused path. I set a _initial_state_ for white path, so that two paths were started from some location. 

![rviz_issue_imu_calib_orig](https://user-images.githubusercontent.com/11235093/77128722-91c38480-6a27-11ea-9130-e13eec75bb73.png)
**Figure 2: gps fused path and offline filtered imu fused path**

In Figure 2, I re-do  _imu_filter_madgwick_  offline for the imu raw data, and take this filtered data for ekf fuse. I am using exactly the same setup. The only difference is the imu input for ekf. The Fig.1 using from rosgbag, the Fig.2 using from offline processed. Basically, those two filtered imu data are same thing. There is always have a drift about 99.2 degree at the beginning.

The reason I re-do filter imu raw data, because I try different imu parameters for ekf. But here, I am using the same imu parameters.

Any one can give me some suggestions. Thanks.

**Comment by ayrton04** [comment]
Thanks for the question. However, all questions should be directed to answers.ros.org. If you've already posted the question there, I'd ask for your patience, as I am extremely busy these days and have less and less time to devote to this package.

In any case, feel free to add the link to the ROS Answers question, whenever it gets/was posted.

**Comment by linzha0** [comment]
hi, I've post a ROS Answers question here: https://answers.ros.org/question/353573/weird-initial-path-from-robot_localizations-ekf-node/
Please give me some suggestions and thanks for your help.
