### ISSUE TITLE
Fusing odom, imu, magnetometer

### ISSUE THREAD

**Issue by elgarbe** [cra-ros-pkg/robot_localization#551]
Hi, I'm looking for information about fusin odometry with imu and magnetometer.
My sensors are connected to an embbeded systems and I'm publishing raw data to ROS using rosserial.
Right now I'm publishing odometry, IMU (raw Gyro and accel data) and raw (after calibration) magnetometer data. I'm not providing orientation data, just raw data.
What is better, fusing all raw data in robot_localization? make some complimentary filter between gyro and magnetometer and publish orientation?

thank

**Comment by SteveMacenski** [comment]
Please ask on ROS Answers
