### ISSUE TITLE
When calculate innovationSubset(z-Hx), why it's  (measurementSubset - stateSubset)?

### ISSUE THREAD

**Issue by KarasCvs** [cra-ros-pkg/robot_localization#586]
https://github.com/cra-ros-pkg/robot_localization/blob/9277d982fa1a2d2a05eec4f59b4f8696ca903f1c/src/ekf.cpp#L100
https://github.com/cra-ros-pkg/robot_localization/blob/9277d982fa1a2d2a05eec4f59b4f8696ca903f1c/src/ekf.cpp#L164
I may get something wrong, but It seems like L164 only calculated (z - x) to me.
If innovationSubset means (z - Hx), shouldn't it be (measurementSubset - stateToMeasurementSubset*stateSubset)?

**Comment by ayrton04** [comment]
First, keep in mind that `H` is a matrix of size `measurement_size x state_size`.  Let's imagine we have a measurement of size 3. The matrix would be 3x15, with 1s in the locations of the updated variables, and 0s elsewhere.

Given that, we could compute the innovation two ways:

1. `innovation = (measurement - H * full_state)`

This would yield a 3x1 - 3x15 * 15x1 -> 3x1 vector, which is correct. In this case, `H * full_state` is just "ignoring" all the variables we don't care about. That would make it identical to `state_subset`.

2. Build the state subset directly, and just use that.

(2) requires fewer iterations, so we do that.

If `H` were actually transforming the data in any way, we couldn't get away with this.

**Comment by KarasCvs** [comment]
> First, keep in mind that `H` is a matrix of size `measurement_size x state_size`. Let's imagine we have a measurement of size 3. The matrix would be 3x15, with 1s in the locations of the updated variables, and 0s elsewhere.
> 
> Given that, we could compute the innovation two ways:
> 
> 1. `innovation = (measurement - H * full_state)`
> 
> This would yield a 3x1 - 3x15 * 15x1 -> 3x1 vector, which is correct. In this case, `H * full_state` is just "ignoring" all the variables we don't care about. That would make it identical to `state_subset`.
> 
> 1. Build the state subset directly, and just use that.
> 
> (2) requires fewer iterations, so we do that.
> 
> If `H` were actually transforming the data in any way, we couldn't get away with this.

Thank you for the explanation, now everything is clear.

**Comment by improve100** [comment]
if measurementSubset were not stateSubset, could expand updateVector_ to really H
