### ISSUE TITLE
Does the covariance is related to the velocity and acceleration?

### ISSUE THREAD

**Issue by improve100** [cra-ros-pkg/robot_localization#587]
As I accelerate, I find that the covariance is related to my acceleration and my velocity.
I check the code found this:

double dFx_dP = (xCoeff * xVel + yCoeff * yVel + zCoeff * zVel) * delta +
                    (xCoeff * xAcc + yCoeff * yAcc + zCoeff * zAcc) * oneHalfATSquared;
    
double dFR_dP = (cpi * cpi * sr * pitchVel + cpi * cpi * cr * yawVel) * delta;

transferFunctionJacobian_(StateMemberX, StateMemberPitch) = dFx_dP;

It's say that the Jacobian matrix is related to the velocity and acceleration. 
When the velocity increases, the covariance of the entire EKF will increase, not only related to the time?
If I set a threshold of covariance, when I go too fast, I'm going to report an error very quickly.

**Comment by Timple** [comment]
Cross post: https://answers.ros.org/question/360182/does-the-covariance-is-related-to-the-velocity-and-acceleration/

**Comment by ayrton04** [comment]
I've been behind on my ROS answers attentiveness, but I'll try to catch up this week. Questions should only go there, thanks.
