### ISSUE TITLE
 odometry from robot_localizaton is not good

### ISSUE THREAD

**Issue by Fanny-one** [cra-ros-pkg/robot_localization#597]
Hi,
I'm trying  use robot_localization to fuse odometry and imu, But I meet some issues .I will provide my bag and paramer here.
[https://github.com/Fanny-one/fuse-odometry-and-imu](url)

the first issue:
when the robot stands still, position x an y of odometry from robot_localization will still move  a bit.

the second issue:
In my bag, I make the robot move forward 8m, but the result is about 8.18m. I think the error is too big. So I think  my covariance maybe is not fit.

I don't understand why and I need help. thanks in advance.
I have asked at answers.ros.org [https://answers.ros.org/question/362413/odometry-from-robot_localizaton-is-not-good/](url)

**Comment by SteveMacenski** [comment]
Please don’t cross post from Answers. Closing.
