### ISSUE TITLE
How is Absolute Heading Reflected on Imu Data?

### ISSUE THREAD

**Issue by jinbae9875** [cra-ros-pkg/robot_localization#599]
Hi, I'm in my first co-op rotation and I'm working on using navsat_transform_node to transform GPS to odom frame. However, the magnetometer in our robot is unusable because of bad interference, so I was thinking I could take a GPS reading before and after traveling for a few meters and calculate the bearing from there. However, how can I take that bearing and turn it into an imu message (to set up navsat_transform?)? I don't quite understand how you can tell whether the x axis is aligned with the East or the North just by looking at the quaternion included in the imu data. How does navsat_transform read imu message and extract the absolute heading from there? I apologize for a noob question. Thanks.

**Comment by ayrton04** [comment]
Hi there,

I meant to update this previously: we ask that all questions be directed to answers.ros.org. Thanks!
