### ISSUE TITLE
Navsat_transform_node Without Magnetometer on Husky Gazebo Sim

### ISSUE THREAD

**Issue by jinbae9875** [cra-ros-pkg/robot_localization#600]
Hi, I'm working on using navsat_transform_node to transform GPS to odom frame. However, the magnetometer in our robot is unusable because of bad interference, so I wrote a node that takes an initial GPS coordinate, moves the robot for 5 meters, take another GPS coordinate, and calculate the yaw using the following script:

	y = np.sin(lon2-lon1) * np.cos(lat2)

	x = np.cos(lat1) * np.sin(lat2) - np.sin(lat1) * np.cos(lat2) * np.cos(lon2 - lon1)

	theta = np.arctan2(y, x)

	yaw = (theta + 2 * np.pi) % (2 * np.pi)

Then I'm generating an IMU message by setting pitch and roll to 0 and converting YPT to quaternion . Since our robot is in repair, I'm testing my node using husky gazebo simulation. After disabling the hector IMU plugin, I'm launching husky_empty_world.launch, gmapping.launch, move_base.launch from the husky packages, navsat_transform_template.launch from robot_localization, and then running my node which takes GPS coordinates, moves the robot, and publishes an IMU message. However, navsat_transform_node doesn't seem to be unsubscribing from the IMU topic after I publish my IMU message (I added a line of ROS_INFO_STREAM("UNSUBSCRIBED") after imu_sub.shutdown(); ). Is this because I'm not publishing the IMU message within a set time frame after the navsat_trasnform_node launches? navsat_transform_node only requires one IMU reading, right? Any help will be appreciated. Thanks.

**Comment by ayrton04** [comment]
Hi there,

Please direct all questions to answers.ros.org. Thanks.

**Comment by jinbae9875** [comment]
Moving this to answers.ros.org
