### ISSUE TITLE
Failed to meet update rate!

### ISSUE THREAD

**Issue by mjs973** [cra-ros-pkg/robot_localization#601]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - source from git repo
- Version or commit hash:
  - HEAD of melodic-devel branch

#### Description

We are running the ekf_localization_node on a Clearpath Jackal.

Commit edc5bea3 causes the performance of the filter to be very poor, and the node continuously logs the warning "Failed to meet update rate!" This message happens many times per second.

This commit causes an access to the ros parameter server for every IMU packet that arrives. On the Jackal, this message comes into the filter at 75 Hz, so the node is trying to access the parameter server every 13 milliseconds. In our environment, the ROS master and parameter server do not run locally on the robot. The robot communciates over a wireless link to a server, and this param() call sometimes takes > 50 milliseconds to execute. That causes input queue overflow and very erratic timing of the filter update callback.

One way to fix this is to cache the silent_tf_failure flag in the RosFilter class. I will submit a pull request shortly.

#### Steps to reproduce issue

See descrption.

#### Expected behavior

See description.

#### Actual behavior

See description.

**Comment by ayrton04** [comment]
That does sound problematic. Given that you know the issue, can you submit a PR to fix it? Just make it a member variable and load the parameter once.
