### ISSUE TITLE
Fusing the  gps and imu datas, the z coordinate data he

### ISSUE THREAD

**Issue by keguo1119** [cra-ros-pkg/robot_localization#603]
## Bug report

**Required Info:**

- Operating System:
  -  OS and version (e.g. Ubuntu 18.04) 
- Installation type:
  -  from source 
- Version or commit hash:
  -  melodic-devel, HEAD, 9277d982fa1a2d2a05eec4f59b4f8696ca903f1c 

#### Steps to reproduce issue
I used the test1.bag to test the pkg performance and the z coordinate data has drifted as the follow pictures.
Can anybody explain why?
![Screenshot from 2020-10-14 16-35-34](https://user-images.githubusercontent.com/31883681/95967409-ca510280-0e3e-11eb-9a04-23271a2a049a.png)
![Screenshot from 2020-10-14 16-36-00](https://user-images.githubusercontent.com/31883681/95967461-dd63d280-0e3e-11eb-93c9-d9d0d45e5c6f.png)

**Comment by ayrton04** [comment]
Hi, all questions should be asked on answers.ros.org. Please post the config you are using when you ask your question.

**Comment by keguo1119** [comment]
![navsat_transform_template](https://user-images.githubusercontent.com/31883681/95983085-a0eea180-0e53-11eb-9f69-e8e05d3e5f61.png)
![ekf_template](https://user-images.githubusercontent.com/31883681/95983088-a1873800-0e53-11eb-91ea-f0da48711488.png)

**Comment by ayrton04** [comment]
Please post this question on answers.ros.org.
