### ISSUE TITLE
topic with state information

### ISSUE THREAD

**Issue by alme96** [cra-ros-pkg/robot_localization#608]
Hi everyone,

I wanted to ask about the topic on which the ekf estimator publishes the estimated state vector.
If I run my system (made of a radar and an imu) I get the following topics:

/accel/filtered
/diagnostics
/imu
/odometry/filtered
/rosout
/rosout_agg
/set_pose
/tf
/tf_static
/ti_mmwave/radar_odom
/ti_mmwave/radar_scan
/ti_mmwave/radar_scan_markers
/ti_mmwave/radar_scan_pcl

The ekf_se node give me this information:
Node [/ekf_se]
Publications: 
 * /accel/filtered [geometry_msgs/AccelWithCovarianceStamped]
 * /diagnostics [diagnostic_msgs/DiagnosticArray]
 * /odometry/filtered [nav_msgs/Odometry]
 * /rosout [rosgraph_msgs/Log]
 * /tf [tf2_msgs/TFMessage]

Subscriptions: 
 * /imu [unknown type]
 * /set_pose [unknown type]
 * /tf [tf2_msgs/TFMessage]
 * /tf_static [unknown type]
 * /ti_mmwave/radar_odom [nav_msgs/Odometry]

Services: 
 * /ekf_se/enable
 * /ekf_se/get_loggers
 * /ekf_se/set_logger_level
 * /ekf_se/toggle
 * /set_pose

but none of the topics /accel/filtered, /diagnostics or /odometry/filtered gives me any msg file with the state vector if I use the command rostopic echo.

Probably I have an error somewhere. But just to know: which is the topic from where I can look at the estimated state vector and realize if the estimation is working properly or not?

Thank you for your help.

Have a good time,

alme96

**Comment by ayrton04** [comment]
Thanks for the question. However, we ask that all questions be directed to answers.ros.org. Thanks!
