### ISSUE TITLE
Ignoring odometry/gps with dual ekf example

### ISSUE THREAD

**Issue by bjajoh** [cra-ros-pkg/robot_localization#614]
Hi,

I'm running the dual ekf example config with all valid data and it seems to be that the second global ekf is just ignoring the transformed position and not updating at all. Covariances are correct, the filtered corariance gets insanly large and still doesnt't update with the RTK position. The filtered and gps pose are really close together at the start and then drift away, it is simply never updating.

Do you have any idea what might be wrong?

I'm using ROS noetic.

**Comment by ayrton04** [comment]
Thanks for the question. However, all questions should be directed to answers.ros.org.
