### ISSUE TITLE
Not providing "FindGeographicLib.cmake" in CMAKE_MODULE_PATH

### ISSUE THREAD

**Issue by AxelCORNILLEAU** [cra-ros-pkg/robot_localization#636]
## Bug report

After installing GeographicLib1.51 on Jetson Xavier, CMakelist.txt points /usr/share/cmake/GeographicLib/ at set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "/usr/share/cmake/GeographicLib/") while the installation of GeographicLib1.51 points /usr/local/share/cmake/GeographicLib/.
Replacing set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "/usr/share/cmake/GeographicLib/") for set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "/usr/local/share/cmake/GeographicLib/") fixed the issue

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - Jetson Xavier
- Version or commit hash:  Latest
  - Latest

#### Steps to reproduce issue

On Jetson Xavier with Ubuntu18.04
Download and install GeographicLib1.51 with https://geographiclib.sourceforge.io/html/install.html
Download robot_localisation from git
#### Expected behavior
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "/usr/share/cmake/GeographicLib/")
#### Actual behavior
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "/usr/local/share/cmake/GeographicLib/")
#### Additional information
reported also [Here](https://answers.ros.org/question/374191/geographiclib151-on-jetson-xavier-for-robot_localization/)

**Comment by SteveMacenski** [comment]
Did you install using rosdep? If not, then we probably won't support you in it, there's a toolchain tested for a reason 

Also, `latest` is not a valid version, please fill out the template with your actual info.

**Comment by AxelCORNILLEAU** [comment]
I did not. I mostly raised this issue for people who will google the issue, as this is how most of people do. Also thx for the rosdep tip, I didn't used it.

**Comment by SteveMacenski** [comment]
OK, closing - ROS Answers was probably the right place for this problem
