### ISSUE TITLE
EKF can't fusion pose0 

### ISSUE THREAD

**Issue by Mingchi-Yeh** [cra-ros-pkg/robot_localization#642]
## Bug report

**Required Info:**

- Operating System:
  Ubuntu 18.04
- Installation type:
  from source

#### Steps to reproduce issue
I use ekf to fusion my odom0 (nav_msgs/Odometry) and pose0 (geometry_msgs/PoseWithCovarianceStamped) result , but the ekf result still like my odom0 result.
I try to use only odom0(nav_msgs/Odometry) and pose0 (geometry_msgs/PoseWithCovarianceStamped) result to run ekf ,but only odom have ekf result , when I only use pose0 to run ekf , /tf don't give me any feedback.
How could I do that I can fusion all my result to opitimize my final result?

**Comment by ayrton04** [comment]
Thanks for the question. However, I ask that all questions be asked on answers.ros.org. If you have already asked there, then I will answer as soon as I can.
