### ISSUE TITLE
Integrate Visual Odometry to Robot Localization

### ISSUE THREAD

**Issue by quangvu16** [cra-ros-pkg/robot_localization#659]
I watch the document. It showed that![image](https://user-images.githubusercontent.com/68116625/117000364-28760200-ad0b-11eb-9705-f32875ea28c7.jpeg)

Robot localization integrates Visual Odometry, IMU, GPS, wheel encoders.

Please help me know how to adjust my file (based on Alex's github) to integrate Visual Odometry from Microsoft Kinect 1 dept camera.

https://github.com/alex-makarov/robaka-ros/blob/master/conf/robot_localization.yaml

Thank you.

**Comment by ayrton04** [comment]
Hi there,

Thanks for the question. However, we ask that all questions be asked on answers.ros.org.

Thanks!
