### ISSUE TITLE
robot_localization: navsat_transform_node runtime error 

### ISSUE THREAD

**Issue by technixol** [cra-ros-pkg/robot_localization#661]
## Bug report

When attempting to run the navsat_transform_node from a cloned foxy-devel the following output is received and the node crashes:

_terminate called after throwing an instance of 'rclcpp::exceptions::ParameterAlreadyDeclaredException'
what(): parameter 'broadcast_utm_transform' has already been declared_

**Required Info:**

**- Operating System:**
Ubuntu 20.04.2 LTS

**- Installation type:**
Source (branch: foxy-devel)

**- Version or commit hash:**
3.1.1

**#### Steps to reproduce issue**
1. git clone -b foxy-devel https://github.com/cra-ros-pkg/robot_localization.git
2. colcon build --packages-select robot_localization
3. source install/setup.bash
4. ros2 run robot_localization navsat_transform_node

**#### Expected behavior**
The node will run without a runtime error

**#### Actual behavior**
Node crashes with the following console output:
_terminate called after throwing an instance of 'rclcpp::exceptions::ParameterAlreadyDeclaredException'
what(): parameter 'broadcast_utm_transform' has already been declared_

**#### Additional information**
Question was asked on ROS.org a the problem was solved by another user. A link to this question is below:
https://answers.ros.org/question/378284/robot_localization-navsat_transform_node-runtime-error/

**Comment by SteveMacenski** [comment]
A PR would be appreciated, sounds like something was accidentally declared twice

**Comment by SteveMacenski** [comment]
This was resolved in https://github.com/cra-ros-pkg/robot_localization/pull/613
