### ISSUE TITLE
 the tf2 dependency will be automatically indexed to the melodic directory

### ISSUE THREAD

**Issue by miku54** [cra-ros-pkg/robot_localization#664]
## Bug report

**Required Info:**

- Operating System:
  - 
- Installation type:
  - 
- Version or commit hash:
  - 

#### Additional information
Hello, when I compile this feature pack, the tf2 dependency will be automatically indexed to the melodic directory. Is there a solution to this problem?

**Comment by SteveMacenski** [comment]
What does this mean, please fill out the actual issue template as requested or this will be closed
