### ISSUE TITLE
Exception thrown from ros_filter.cpp during launch in ROS2 galactic

### ISSUE THREAD

**Issue by kribe48** [cra-ros-pkg/robot_localization#674]
## Bug report

Exceptions are thrown when running code in ROS2 galactic. I believe the reason is due to the change in the declaration of parameters, which in galactic all are given a specific type. Parameters that are not set with default values can therefore not be used to check if parameter values have been provided.

One example is on line 822-823 in ros_filter.cpp:
this->declare_parameter<std::string>("tf_prefix"); 
if(this->get_parameter("tf_prefix", tf_prefix_path)) { ....

- Operating System:
Ubuntu 20.04
- Installation type:
Source
- Version or commit hash:
galactic

#### Steps to reproduce issue
Build the code and launch e.g. dual_ekf_navsat_example.launch.py

#### Expected behavior
No exceptions thrown

#### Actual behavior
Exception:  what():  expected [string] got [not set]

**Comment by jacobperron** [comment]
Sorry, I introduced this bug in #663. See https://github.com/cra-ros-pkg/robot_localization/pull/675 for a fix.
