### ISSUE TITLE
Error trying to run ekf_node on ros2 galactic, but it works on ros2 foxy

### ISSUE THREAD

**Issue by j-corvo** [cra-ros-pkg/robot_localization#685]
Hello,

Thanks in advance for your help!

I'm having a nightmare trying to figure out what's wrong with my code. I just installed ros2 galactic and I'm running the code that works on ros2 foxy. When I launch the robot_localization package it works fine on ros2 foxy, but in galactic I'm having this error:

**[ekf_node-1] terminate called after throwing an instance of 'rclcpp::ParameterTypeException' [ekf_node-1]   what():  expected [string] got [not set]**

I changed to galactic because It has a lot of improvements that are very useful for my thesis project so It would be much appreciated some help to get it to work in this distro.

Here is the screenshot of the terminal:

![galactic](https://user-images.githubusercontent.com/52609366/126571896-fa67c882-9272-4b56-a586-d35750320948.png)

**This is my configuration file:**

ekf_filter_node:
    ros__parameters:

        two_d_mode: false
        publish_acceleration: false
        publish_tf: true

        map_frame: map              
        odom_frame: odom            
        base_link_frame: base_link  
        world_frame: odom          

        odom0: /lgsvl/gps/odom
        odom0_config: [true,  true,  true,
                       false, false, false,
                       false, false, false,
                       false, false, true,
                       false, false, false]

        imu0: /lgsvl/imu
        imu0_config: [false, false, false,
                      true,  true,  true,
                      false, false, false,
                      false, false, false,
                      false, false, false]

        process_noise_covariance: [0.05, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
        0.0,    0.05, 0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
        0.0,    0.0,    0.06, 0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    0.03, 0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    0.03, 0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    0.06, 0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.025, 0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.025, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.04, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.01, 0.0,    0.0,    0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.01, 0.0,    0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.02, 0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.01, 0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.01, 0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.015]

        initial_estimate_covariance: [1e-9, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
        0.0,    1e-9, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
        0.0,    0.0,    1e-9, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    1e-9, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    1e-9, 0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    1e-9, 0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9, 0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9, 0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9, 0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9,  0.0,     0.0,     0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     1e-9,  0.0,     0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     1e-9,  0.0,    0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     1e-9, 0.0,    0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    1e-9, 0.0,
        0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    1e-9]`

**And this is my launch file:**

```
from launch import LaunchDescription
from launch_ros.actions import Node
from ament_index_python.packages import get_package_share_directory
import os


robot_localization_params = os.path.join(
            get_package_share_directory('navigation'),
            'config',
            'robot_localization_params.yaml'
        ),


def generate_launch_description():
    return LaunchDescription([
        Node(
          package='robot_localization',
          executable='ekf_node',
          name='ekf_filter_node',
          output='screen',
          parameters=[
            robot_localization_params
            ]
        )
    ])

```

Any ideas of what it can be?

**Comment by j-corvo** [comment]
@MCFurry

**Comment by SteveMacenski** [comment]
Please search for that error, I'm sure you'll find immediately if you do so.

**Comment by j-corvo** [comment]
Yeah, but what I found is what the error message says. Somewhere in my parameters file, there is one parameter that should be a string, but when I replaced that file with the ekf.yaml example in this repository, it had no effect. As I am a beginner in ROS2 it could be that my launch file is not correct or so.

What is weird is that it works on foxy but does not on galactic and for what I know robot_localization didn't change for that much from foxy to galactic, at least in terms of parameters and syntax.

And that's why I posted it here because someone more experienced could spot my error.

**Comment by emilnovak** [comment]
I had a similar complication yesterday. You will need to add the package to your workspace and build it from source. Either change the src/ros_filter.cpp code to match the one on the ros2 branch or fork the galactic-devel branch just cherry pick [this](https://github.com/cra-ros-pkg/robot_localization/commit/3b2cb792abe0261aa55e6f3f4ad49d7efebcdbd6) commit from the ros2 branch. This alone may not solve the whole getting the foxy branch working problem so take a look at this [issue](https://github.com/cra-ros-pkg/robot_localization/issues/622) as well.

**Comment by Serafadam** [comment]
I'm having same issues, fixed them with solution above

**Comment by Jconn** [comment]
to expand on what @emilnovak said, the galactic sync currently _requires_ the params in that cherry-pick to be set, things like:
```
tf_prefix
control_config
acceleration_limits,
```
if you don't have these params set, you'll get an exception on node launch. That cherry-pick commit will give all of these parameters a default value, which will stop the exception from being thrown if the params aren't manually set by the roboticist.

**Comment by cesar-lopez-mar** [comment]
I have created a branch with the right cherry-picks here: https://github.com/nobleo/robot_localization/tree/fix/galactic%2Fload_parameters

**Comment by SteveMacenski** [comment]
Please submit a PR
