### ISSUE TITLE
missing geographiclib dependency in package.xml for melodic

### ISSUE THREAD

**Issue by joshjowen** [cra-ros-pkg/robot_localization#688]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  -  Binaries from Apt
- Version or commit hash:
  - From apt: 2.6.11-1bionic.20210723.234509

#### Steps to reproduce issue
Install using sudo apt install ros-melodic-robot-localization

#### Expected behavior
libgeographic-dev is installed as a dependency 
#### Actual behavior
libgeographic-dev is not installed as a dependency 
#### Additional information
geographiclib is listed in the package.xml for the noetic release which solves the problem there but was not included in the melodic release

**Comment by ayrton04** [comment]
It's in the `melodic` branch, it's just a `build_depend`:

https://github.com/cra-ros-pkg/robot_localization/blob/melodic-devel/package.xml#L36

Would you care to submit a PR?
