### ISSUE TITLE
How to use this package with only IMU sensor input?

### ISSUE THREAD

**Issue by BojanAndonovski71** [cra-ros-pkg/robot_localization#697]
Hi

I have and 9 axis IMU that gives me orientation, angular velocity and linear acceleration. Would like to get the linear velocity from the package. Any help how to configure it and use the launch file?

I guess I can use the ekf_template.launch file as example 

```
<launch>
  <node pkg="robot_localization" type="ekf_localization_node" name="ekf_se" clear_params="true">
    <rosparam command="load" file="$(find robot_localization)/params/ekf_template.yaml" />

    <!--  Placeholder for output topic remapping
    <remap from="odometry/filtered" to=""/>
    <remap from="accel/filtered" to=""/>
    -->

  </node>
</launch>
```

My raw IMU topic is /robot/imu so in that case my launch file would have `<param name="imu0" value="/robot/imu"/>` is that correct?  what about the   <!--  Placeholder for output topic remapping  ` <remap from ..?` and the rigid body (robot) frame is the `base_link`. My IMU frame is `/thrbot/imu_link`

**Comment by ayrton04** [comment]
Please ask questions on answers.ros.org.
