### ISSUE TITLE
A Question Regarding The Omnidirectional Model

### ISSUE THREAD

**Issue by omar2057-ah** [cra-ros-pkg/robot_localization#702]
Is it okay to use robot_localization on an ackermann-steered vehicle, since the kinematic models are different.
From my understanding, it won't be a problem since the omnidirection will predict the state using the velocity control action and the previous pose, in addition to the orientation, so everything will be fine if only the package takes the orientation of the vehicle from the imu not from the differential speeds of the wheels?
Am I right?

**Comment by SteveMacenski** [comment]
Please ask on ros answers
