### ISSUE TITLE
ros_filter.cpp:1158

### ISSUE THREAD

**Issue by ryanyej** [cra-ros-pkg/robot_localization#703]
In member function ‘void robolt_localization::RosFilter<T>::loadParams()’:
/home/robot_localization/src/robot_localization/src/ros_filter.cpp:1158:61: error: no match for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘std::vector<int>’)
                  odomTopicName << " pose update vector is " << poseUpdateVec << "\t"<<
/home/robot_localization/src/robot_localization/include/ros_filter_utilities.h:47:65: note: in definition of macro ‘RF_DEBUG’
 #define RF_DEBUG(msg) if (filter_.getDebug()) { debugStream_ << msg; }

also  a lot of /usr/include/c++/7/ostream:XXX:XX  showed up.
such as:
/usr/include/c++/7/ostream:166:7: note:   no known conversion for argument 1 from ‘std::vector<int>’ to ‘long int’
                                                               
these showed up when i catkin make
I don't understand

**Comment by ayrton04** [comment]
Not convinced there's a bug here. Perhaps you have something about your workspace config that is not right. Please ask this question on answers.ros.org or robotics.stackexchange.com. When you do, please include the ROS distribution you are using, the branch of `robot_localization` you are trying to build, and any other relevant details.
