### ISSUE TITLE
Odometry/ GPS and /GPS /fix

### ISSUE THREAD

**Issue by miku54** [cra-ros-pkg/robot_localization#706]
Hello, I encountered a problem when I fused GPS data using Navsat_transform_node in Robot_localization. Odom1 is Odometry/ GPS, the message data type for this topic is nav_MSgs /Odometry, but my GPS topic is/GPS /fix, The message data type is sensom_MSgs /NavSatFix, so when I run the fusion program, my terminal will display an error. Is Odometry/ GPS generated by conversion required? However, in robot_localization http://docs.ros.org/, I was prompted to input the GPS topic of Sensom_MSgs /NavSatFix. I didn't quite understand this step, and I hope to get your answer. Thank you.
## Bug report
 Client [/outdoor_waypoint_nav/ekf_se_map] wants topic /gps/fix to have datatype/md5sum [nav_msgs/Odometry/cd5e73d190d741a2f92e81eda573aca7], but our version has [sensor_msgs/NavSatFix/2d3a8cd499b9b4a0249fb98fd05cfa48]. Dropping connection.
![864EEC15-8F59-417c-BC3F-505177E63A02](https://user-images.githubusercontent.com/81612531/142797331-03b3f49b-587a-485c-bb1a-c01e024ac967.png)

**Required Info:**

- Operating System:
ubuntu18.04
- Installation type:
  - 
- Version or commit hash:
  -

**Comment by ayrton04** [comment]
HI there, this isn't an issue with this package. You are mixing ROS distributions somehow, and whatever is publishing your `NavSatFix` message is using a different version of that message than your workspace. I suggest cleaning and rebuilding your entire workspace, and making sure that if you have `sensor_msgs` cloned in your workspace, it matches the version in your ROS distro. If this data is from a bag, then the bag is using an old format for that message.
