### ISSUE TITLE
Yaw-offset and magnetic declination radiance calculation 

### ISSUE THREAD

**Issue by Masoumehrahimi** [cra-ros-pkg/robot_localization#710]
Hi 
Does anybody to explain how to calculate yaw-offset and magnetic declination radiance?
I searched alot bet get more confused and found nothing 
Thanks

**Comment by ayrton04** [comment]
In general, it's best to ask questions on answers.ros.org, but for now:

http://docs.ros.org/en/noetic/api/robot_localization/html/integrating_gps.html

**Comment by Masoumehrahimi** [comment]
thank you for closing this issue,
but I am familiar with the link which you mentioned, I did not find the answer because of this asking here

**Comment by ayrton04** [comment]
OK, then please use answers.ros.org, as all questions should be directed there.

**Comment by Masoumehrahimi** [comment]
hi, 
would you please answer my question in ROS answers:
https://answers.ros.org/question/392333/how-to-specify-yaw-offset-and-magnetic-declination-radiance-in-robot_localization-package/
thanks

**Comment by ayrton04** [comment]
I will try to get to it soon. I don't get a lot of cycles to answer questions these days. I have a backlog of questions to answer, and I answer them in the order that they were asked.

**Comment by Masoumehrahimi** [comment]
Dear TOM,
would you please answer my question in ROS answers, I want to do the test, but I get stuck in this part for months!
https://answers.ros.org/question/392333/how-to-specify-yaw-offset-and-magnetic-declination-radiance-in-robot_localization-package/
thanks

**Comment by ayrton04** [comment]
I'll try to get to it soon. I don't get a lot of time to support this package these days, but I'll try to carve out some ROS Answers time this week.
