### ISSUE TITLE
Wrong Robot position at start-up ( misunderstanding delination ? )

### ISSUE THREAD

**Issue by FrGe2016** [cra-ros-pkg/robot_localization#715]
I am using GPS with RTK for the localization

Due to hard winter conditions, I have made my the map with a Survey Android app. and transfered the data to a Geographic information system (QGIS).

I order to be compatible with the navsat_transform. I have used the WGS94 to UTM19N projection in QGIS. I have then Exported the result of my survey as a scaled .pgm file. ( In this format the north has has no declination)

When i launch robot_localization my_dual_ekf_navsat_example.launch with my local declination of 15 deg West. My outdoor fixed antenna ( witch act temporarily as my robot ) appear outside the boundaries of my survey
![Screenshot from 2022-01-16 17-33-52_with_declinaison_15deg_w](https://user-images.githubusercontent.com/16846897/149681955-b81cc6ad-d6cb-475e-b9e6-9febb7f9ff3e.png)

If i remove the declination in my dual_ekf_navsat_example.yaml file. My antenna is at the required location.  
![Screenshot from 2022-01-16 17-29-24_declinaison_0](https://user-images.githubusercontent.com/16846897/149682018-ea2961ad-a3d7-4489-8b43-7d486980180c.png)

If  i leave the yaml_file without declination. Will it generate operation problem with a real moving robot ?

An other solution would be to rotate the map. 

But one way or another i think that i am introducing false information in my control logic.

Am I miss understanding something ?

**Comment by ayrton04** [comment]
Thanks for the question. However, we ask that all questions be directed to answers.ros.org or robotics.stackexchange.com.
