### ISSUE TITLE
No data on /odometry/filtered topic or /accel/filtered

### ISSUE THREAD

**Issue by WUyinwei-hah** [cra-ros-pkg/robot_localization#720]
## No data on /odometry/filtered topic or /accel/filtered 

- Operating System:
Ubuntu 20.04 with ros2-galactic

- Version or commit hash:
Galactic

I run the [sam_bot_description](https://github.com/ros-planning/navigation2_tutorials) with robot_localization package and do everything follow [the tutorial](https://navigation.ros.org/setup_guides/odom/setup_odom.html) but I finally got nothing on  /odometry/filtered topic or /accel/filtered. Same issue was raised [here](https://github.com/ros-planning/navigation2_tutorials/issues/30).
I do some log and find that in [ros_filter.cpp](https://github.com/cra-ros-pkg/robot_localization/blob/galactic/src/ros_filter.cpp) the code can not run into the function **periodicUpdate**, take it a step further the GenericTimer seems useless.

I will appreciate it if anyone can help me.

Please let me know if more information is required about the issue.

**Comment by ayrton04** [comment]
Can you please ask this question on answers.ros.org or on robotics.stackexchange.com? And when you do, please provide your full EKF config and a sample message from every sensor input.

**Comment by WUyinwei-hah** [comment]
> Can you please ask this question on answers.ros.org or on robotics.stackexchange.com? And when you do, please provide your full EKF config and a sample message from every sensor input.

ok, thanks

**Comment by TrH-Thang** [comment]
I have this issue too. How did you solve it?
