### ISSUE TITLE
robots_localization:Transform from gyro_link to base_footprint was unavailable for the time requested. Using latest instead.

### ISSUE THREAD

**Issue by miku54** [cra-ros-pkg/robot_localization#730]
[ WARN] [1645532392.821254984]: Transform from base_footprint to map was unavailable for the time requested. Using latest instead.
and       Transform from gyro_link to base_footprint was unavailable for the time requested. Using latest instead
Required Info:

Operating System:
ubuntu18.04 ros-melodic
Hello , when I use the robots_localization function package to fuse odom, imu, and gps data, the navsat_transform_node node will always flash the following alarms: "Transform from base_footprint to map was unavailable for the time requested. Using latest instead." The frequency of my /odom and /imu topics are both 50hz (but I don't think it has anything to do with the topic's frequency), the frequency of /gps/fix is 100hz, and the running files and parameters are in this repository:https://github.com/miku54/robot_localization-gps

I have asked a related question in this link：[https://github.com/cra-ros-pkg/robot_localization/issues/729](url)
I have raised a related question in ros.org, the link is: [https://answers.ros.org/question/396538/robots_localizationtransform-from-gyro_link-to-base_footprint-was-unavailable-for-the-time-requested-using-latest-instead/](url)
Since there are no credits, my config files are placed in this repository: [https://github.com/miku54/robot_localization-gps](https://github.com/cra-ros-pkg/robot_localization/issues/url)
Examples of sensor inputs are placed in this repository:
[https://github.com/miku54/robot_localization-gps/tree/rosbag](https://github.com/cra-ros-pkg/robot_localization/issues/url)
Do you need more information?

**Comment by ayrton04** [comment]
How is this different than this?

https://github.com/cra-ros-pkg/robot_localization/issues/729

1. Please don't double post.
2. This is not a bug. You are misunderstanding how the filter and tf work.
3. This is also not an error. It is a warning.
4. Please direct all questions to answers.ros.org or robotics.stackexchange.com, and then *please be patient* in waiting for an answer. I don't get a lot of cycles to provide support for this package, so questions are rarely answered immediately.
