### ISSUE TITLE
echo /odometry/filtered no data

### ISSUE THREAD

**Issue by HusamZain** [cra-ros-pkg/robot_localization#740]
Thank you for your great work.
I'm trying to use this package, for further implementation  in NAV2 project .
I'm using Ros2 galactic on jetson nano, and I wanted to fuse data from wheel encoder and IMU 
I manged to publish the [nav_msgs/Odometry](http://docs.ros.org/api/nav_msgs/html/msg/Odometry.html) on the **/odom** topic 
and [sensor_msgs/Imu](http://docs.ros.org/api/sensor_msgs/html/msg/Imu.html) on the **/imu** topic, also all the needed transformations are sat up (odom to base_link ) and ( base_link to imu) 
so, my data are ready for fusion.

when I run the **ekf_node** it's subscribing to the **/odom** and **/imu** topics and publishing the different topics such as **/odometry/filtered** 
![Screenshot from 2022-03-23 15-39-19](https://user-images.githubusercontent.com/97671800/159731321-88362eaa-39bb-4fb4-bd60-00a1230e42d7.png)
However, when I check the data published from these topics (**/odometry/filtered** ) using `ros2 topic echo /odometry/filtered` , I found that there is no data, as here
![Screenshot from 2022-03-23 16-38-35](https://user-images.githubusercontent.com/97671800/159737905-e692552e-15f4-4092-ab42-d6d1bede6271.png)

I checked both topics (**/odom** and **/imu** ) and they are publishing the **nav_msgs/Odometry** and **sensor_msgs/imu**  and everything looks just fine , does anyone has an idea what could be the issue that there are no data published by the **ekf_node**  ?

I used `ros2 topic echo /diagnostics ` and this what I got, not sure if it's useful.

![Screenshot from 2022-03-23 15-41-14](https://user-images.githubusercontent.com/97671800/159731575-ae8b3902-09f5-4d5e-9c76-249d870de0f8.png)

 also this a snippet from my config ekf.yaml

![Screenshot from 2022-03-23 16-07-20](https://user-images.githubusercontent.com/97671800/159731357-d4396cbd-bbd4-4565-a896-7acabf0a39eb.png)

I tried also use just one data source (/odom or /imu ) to reduce error source, but still the same  result.

**Comment by ayrton04** [comment]
Thanks for the question. However, all questions should be asked on answers.ros.org or robotics.stackexchange.com. When you do post a question, please include your config (and not as an image) and a sample message from each sensor input.

**Comment by tsadarsh** [comment]
Hi, @ayrton04. I have the exact same issue that is faced by @HusamZain. 

I have asked the question in answers.ros.org. [Here](https://answers.ros.org/question/411025/what-should-be-published-in-clock-when-using-a-real-robot/) is the link to my question. I also made sure to include the config file in the question. Can you please help me with this issue?

p.s. @HusamZain Did you get this issue solved already?

**Comment by tsadarsh** [comment]
I solved this issue. The problem was with my *tf* tree.
