### ISSUE TITLE
[ROS2] ekf_node running slower than set frequency

### ISSUE THREAD

**Issue by HappySamuel** [cra-ros-pkg/robot_localization#741]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries  `$ sudo apt install ros-foxy-robot-localization`
- Version or commit hash:
  - `ros-foxy-robot-localization is already the newest version (3.1.1-1focal.20220204.181349)`

#### Expected behavior
Frequency set at 40.0 Hz

![Screenshot from 2022-03-28 21-22-31](https://user-images.githubusercontent.com/18137963/160407120-d88b6ad0-3ef6-43f8-b6d8-4b1a5ea0dbc2.png)

#### Actual behavior
`$ ros2 topic hz /odometry/filtered` only give 10 Hz

![Screenshot from 2022-03-28 21-19-46](https://user-images.githubusercontent.com/18137963/160407331-465581d9-780f-4dd0-833b-2a8f495ea823.png)

#### Additional information
Hi

I have both `/odom` detected at 50Hz and `/imu/data` detected at 50Hz, but the output of `/odometry/filtered` is only 10Hz. I print out `/diagnostics` and found that the target frequency is 0.0 Hz, which result `message: Frequency too high`. 

I have tested with setting parameter frequency with following values and these are their corresponding result:
| Parameter HZ | Diagnostics Target Hz | Diagnostics Actual Hz |
|----------------|-----------------|-----------------|
| 5.0             | 0.0              | 5.0               |
| 8.0             | 0.0              | 8.0               |
| 10.0           | 0.0              | 10.0             |
| 15.0           | 0.0              | 10.0             |
| 20.0           | 0.0              | 10.0             |
| 30.0           | 0.0              | 10.0             |
| 40.0           | 0.0              | 10.0             |

Any idea / suggestion that i can bring it back to desired frequency? Never face this issue when using ekf_node in ROS1, but faced this issue when porting to ROS2.

Best,
Samuel

**Comment by ayrton04** [comment]
Thanks for the question. Before we mark it as a bug (I would hope that someone would have noticed something this serious by now), can you please ask a question on answers.ros.org or robotics.stackexchange.com? Please include your full config and sample messages from each sensor input. It's possible there's just a setting that needs to be changed. I'll reopen this if there is a bug.
