### ISSUE TITLE
Is there any plan to add error-state Kalman filter in robot localization?

### ISSUE THREAD

**Issue by oscar1780** [cra-ros-pkg/robot_localization#745]
Dear author, is there any plan to add ESKF module for this package? As some papers mentioned that ESKF have a better fusing performance than ekf and ukf, i do want write this algrithom by myself, but if u have already raised into the agenda, i will follow this project and test it, casue coding is very hard to me :(

**Comment by ayrton04** [comment]
There are no such plans, but I obviously would consider a PR. It would need to be added as a new filter type.

**Comment by oscar1780** [comment]
> 

OK, ty for ur reply. I would try it myself first, maybe i will push a pr someday.
