### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by Timple** [cra-ros-pkg/robot_localization#768]
It's been over a year that a noetic release was made. PR #705 and PR #728 look like useful improvements.

Could a new release be triggered for Noetic?

**Comment by ayrton04** [comment]
Yes, apologies. Will try to get to that today.

**Comment by ayrton04** [comment]
https://github.com/ros/rosdistro/pull/33983

**Comment by Timple** [comment]
Just after the last sync. So plenty of room to test.
Thanks!
