### ISSUE TITLE
build robot_localization inside docker

### ISSUE THREAD

**Issue by an99990** [cra-ros-pkg/robot_localization#769]
Hi,
I am trying to build robot_localization inside a docker and currently running into issues with GeographicLib. I have installed it via sudo apt-get install libgeographic-dev like suggested in [issue](https://github.com/ethz-asl/rotors_simulator/issues/520) 

I also tried copying the file
`sudo ln -s /usr/share/cmake/geographiclib/FindGeographicLib.cmake /opt/conda/share/cmake-3.21/Modules/`

`ln: failed to create symbolic link '/opt/conda/share/cmake- .21/Modules/FindGeographicLib.cmake': File exists`

but i still get the same issue.

error_log 

```
CMake Error at /opt/conda/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find GeographicLib (missing: GeographicLib_LIBRARY_DIRS
  GeographicLib_LIBRARIES GeographicLib_INCLUDE_DIRS)
Call Stack (most recent call first):
  /opt/conda/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/geographiclib/FindGeographicLib.cmake:36 (find_package_handle_standard_args)
  CMakeLists.txt:39 (find_package)
```
Anyone has an idea on how to solve this ?

**Comment by SteveMacenski** [comment]
Ask on ROS Answers
