### ISSUE TITLE
IMU with LiDar Fusion

### ISSUE THREAD

**Issue by h2jaafar** [cra-ros-pkg/robot_localization#773]
Hello,

Sorry if this is a trivial question;

I am trying to use slam_toolbox, and I require a odom to base_link transform, as well as odometry data. 
We don't have wheel encoders on this specific robot, only LiDar and IMU. 

My question is: will the sensor fusion of the lidar and imu be sufficient? Or is it necessary to have wheel encoders to provide a relatively accurate result?

**Comment by ayrton04** [comment]
Hi, thanks for the question. However, we ask that all questions be directed to answers.ros.org or robotics.stackexchange.com.
