### ISSUE TITLE
Pythong code for robot localisation (EKF)

### ISSUE THREAD

**Issue by Masoumehrahimi** [cra-ros-pkg/robot_localization#774]
Hi, 
Is there any python code for using robot localisation pkg?
I want to fuse imu, wheel odometer, gps, with slam odometry information through applying extended kalman filter. is there any code?

thanks

**Comment by ayrton04** [comment]
I'm not sure I understand the question. The package is written in C++. In any case, questions should go to ROS Answers, please.
