### ISSUE TITLE
Parametrization of Rotation

### ISSUE THREAD

**Issue by Jad-Tawil** [cra-ros-pkg/robot_localization#779]
After inspecting the code, it seems like the parameterization of rotation is done in roll / pitch / yaw angles. The innovation is normalized to avoid discontinuous jumps around pi/-pi, and after the state is updated, the angles are wrapped
.
I have read elsewhere that using roll / pitch / yaw is inadvisable because they are discontinuous and singular. Using quaternions is a better option. 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6339217/

Would you care to comment on this ?

**Comment by ayrton04** [comment]
Yes, well aware that quaternions are preferable for numerous reasons. But this package is really in a "maintain" state at this point, with our focus moving to [fuse](https://github.com/locusrobotics/fuse). So I don't see it changing.

**Comment by Jad-Tawil** [comment]
Thank you Tom, I am looking into fuse atm. I see it is using graph optimization instead of kalman filter. In graph optimization, is the parameterization of rotation i mentioned at play?

**Comment by ayrton04** [comment]
The kinematic model is independent of the underlying sensor fusion algorithm. Kalman filters can use quaternions and factor graphs can use Euler angles.

Unlike this package, which assumes a single kinematic model, `fuse` is built from the ground-up to allow any kind of kinematic model (or sensor model). For example, the package has constraints for 3D rotations represented as quaternions or Euler angles:

https://github.com/locusrobotics/fuse/blob/devel/fuse_constraints/src/absolute_orientation_3d_stamped_constraint.cpp
https://github.com/locusrobotics/fuse/blob/devel/fuse_constraints/src/absolute_orientation_3d_stamped_euler_constraint.cpp

It's up to the user to work with (or create) the plugins that are best suited to their problem.

**Comment by Jad-Tawil** [comment]
That makes sense! Looks like a great package. Well done!

**Comment by ayrton04** [comment]
Credit is entirely to my colleague @svwilliams!
