### ISSUE TITLE
Is there any plan to port it without ros?

### ISSUE THREAD

**Issue by charles-lyc** [cra-ros-pkg/robot_localization#781]
Hi, I want to use robot localiztion in my project, but I use a tiny platform which support c++ but could never run ROS or Ubuntu neither. 
Is there any way to port these source code into my project in kinda painless way? Thx~~

**Comment by SteveMacenski** [comment]
Almost certainly not.

**Comment by ayrton04** [comment]
The core classes are generally ROS-agnostic, but you'll need Eigen. Also, the `RosFilter` class does a lot of bookkeeping. I'm not sure how useful the package would be without that.

In any case, this package was always meant to work in the ROS ecosystem, and I have no plans to port it to non-ROS platforms.

**Comment by charles-lyc** [comment]
OK, thx 4 your reply~~
