### ISSUE TITLE
Release for Humble and Rolling?

### ISSUE THREAD

**Issue by ijnek** [cra-ros-pkg/robot_localization#782]
Hi @ayrton04, thanks for maintaining this library. May I request for a release in Humble and Rolling? Both distros' latest releases are version 3.3.1, and since then https://github.com/cra-ros-pkg/robot_localization/issues/732 has been resolved. This issue is currently making navsat_transform_node unusable for everyone, as it throws an error immediately after start up.

**Comment by SteveMacenski** [comment]
@ayrton04 I can handle this, I'm planning on running Nav2 / SLAM Toolbox syncs on Friday anyway. I can add this to the list. Will release on Friday.

**Comment by ijnek** [comment]
Thanks @SteveMacenski.

**Comment by ayrton04** [comment]
Thanks, Steve.
