### ISSUE TITLE
ROS 2 - Install include directory

### ISSUE THREAD

**Issue by oKermorgant** [cra-ros-pkg/robot_localization#784]
Hi, 

We are building a package based on `robot_localization` to allow tight coupling with range / bearing measurements.
It basically boils down to using the provided EKF but adding new measurement types (range to anchors).

In order to compile our package we currently need to have a clone of `robot_localization` because the headers are not installed.

Would it be possible to install the `include` directory in the CMakeLists in order to avoid having to keep a local copy of the whole code?
The linking step with `rl_lib` is already fine, really what is missing to use `robot_localization` code in another project are the headers.

Thanks,

**Comment by SteveMacenski** [comment]
Sounds reasonable. Can you open a PR to ament export the includes? That should do the trick. If you can do it in the next couple of hours, I can get that out in my releases today.
