### ISSUE TITLE
Is IMU tf needed when fuse odom and IMU

### ISSUE THREAD

**Issue by spcrobocar** [cra-ros-pkg/robot_localization#792]
I am trying to fuse odom and IMU. I have two ways to install my IMU on the robot. One way is to point the IMU up, the other way is the point the IMU down. Clearly this will impact the IMU measurements. When I change how the IMU is installed on the robot, do I need to change the parameters to run this package?

**Comment by ayrton04** [comment]
Please ask this question on answers.ros.org. If you've already asked, please be patient, as I don't get the cycles to answer r_l questions as much as I'd like these days.
