### ISSUE TITLE
2 IMU + GPS + SLAM

### ISSUE THREAD

**Issue by reinzler** [cra-ros-pkg/robot_localization#793]
Hi, is it possible to fuse data from 2 different IMU ( VN100, Bosh BMI055), GPS (HERE 3) and SLAM from IntelRealSense D455 is it possible? If not, is it possible to fuse data only from 2 IMU (VN100, Bosh BMI055) and GPS (HERE 3)? How should I configurate YAML file in this way? Probably someone has an example config which i could look at? My YAML file linked to this issue. [Thanks.](https://drive.google.com/file/d/1atz9c6A5QiqkkDhTS9q25KgQGwUnTcXC/view?usp=sharing)

**Comment by ayrton04** [comment]
Please ask this question on answers.ros.org. If you've already asked, please be patient, as I don't get the cycles to answer r_l questions as much as I'd like these days.
