### ISSUE TITLE
Is there a parameter to configure the position transform between IMU and GPS sensors?

### ISSUE THREAD

**Issue by 601469588** [cra-ros-pkg/robot_localization#797]

**Comment by 601469588** [comment]
Is there a parameter to configure the position transform between IMU and GPS sensors?

If not,Do we need to consider their position transform?

Or we need to get them close enough?

**Comment by ayrton04** [comment]
All sensors have a `frame_id` in the header. You need to define transforms for those frames from your robot base frame.

If you have further questions, please use answers.ros.org.
