### ISSUE TITLE
Include linear acceleration in state estimate

### ISSUE THREAD

**Issue by ayrton04** [cra-ros-pkg/robot_localization#8]
The state estimate for all of robot_localization's nodes currently include only x, y, z, roll, pitch, yaw, and their respective velocities. However, linear acceleration is often available from acelerometers. This information should be included in the state estimate.

**Comment by tdnet12434** [comment]
Can u confirm my understand , all states are in world-frame right?
Another question is imu acceleration,angular vel inputs are body-frame meanwhile orientation is world frame right?
Thx u advanced.

**Comment by ayrton04** [comment]
No. The EKF and UKF adhere to [REP-105](http://www.ros.org/reps/rep-0105.html), and they assume the incoming messages do as well (or that there is a transform provided to get the input data into the required frames). Specifically, all pose data (position and orientation) are in a world-fixed frame (e.g., _odom_ or _map_), and all velocity data is given in the body frame (e.g., _base_link_). Linear acceleration is also tracked in the body frame, but we don't output it. The output of the node is a [nav_msgs/Odometry](http://docs.ros.org/api/nav_msgs/html/msg/Odometry.html) message, which has a separate field to specify the `frame_id` for the velocity data.
