### ISSUE TITLE
how to set “yaw_offset” and "magnetic_declination_radians" ?

### ISSUE THREAD

**Issue by zhu-bingo** [cra-ros-pkg/robot_localization#803]
how to set “yaw_offset” and "magnetic_declination_radians" ?

**Comment by ayrton04** [comment]
Please read the [package documentation](http://docs.ros.org/en/noetic/api/robot_localization/html/index.html) and check [ROS Answers](https://www.google.com/search?q=site%3A+answsers.ros.org+%22magnetic_declination_radians%22).
