### ISSUE TITLE
Cross-correlation between measurements

### ISSUE THREAD

**Issue by jorissijs** [cra-ros-pkg/robot_localization#807]
I could not find out whether the package is able to deal with cross-correlation between measurements. Not only for the case this is known, but also when this is not known and something like covariance intersection should be used. Is it included, or not?

**Comment by ayrton04** [comment]
The package doesn't have any explicit handling of correlation between separate measurement sources. Cross-correlation is captured in the state estimate via the kinematic model. As an example, if the filter is configured for full 3D state estimation and some sensor data is coming in that only measures XY position, then the Z position covariance will start to grow without bound. If we suddenly get a measurement in Z, the correlation between those variables can cause a shift in the XY position as well (depending on the vehicle's orientation, of course).

In any case, we request that any further questions, if you have them, be directed to answers.ros.org. Thanks!
