### ISSUE TITLE
In this EKF motion model, does the position update constrain velocity?

### ISSUE THREAD

**Issue by improve100** [cra-ros-pkg/robot_localization#812]
Hello, I have looked at the code implementation of the EKF model and I know that the position x, y, z are calculated through several items . 
![image](https://github.com/cra-ros-pkg/robot_localization/assets/6092914/47161379-f9ec-4289-bc00-dc052596a784)

However, I have a question. When only the IMU and position and attitude updated, is the velocity also constrained? It seems that there is no constraint on the velocity in the model. It is possible that I have misunderstood, please help me point it out.

**Comment by ayrton04** [comment]
Please ask on answers.ros.org.
