### ISSUE TITLE
ROS Humble Version Matching Rolling Version No.

### ISSUE THREAD

**Issue by GeorgeTMartin** [cra-ros-pkg/robot_localization#813]
Hello,

We recently had some trouble with robot localization, using an EKF on an RPi robot where the accelerations did not publish. We noticed that the version installed with apt-get for humble is 3.5.0, which appears to be a Rolling release, instead of 3.4.2.

When building from source for 3.4.2, the issue was not present. Should the debian package for Humble be 3.4.2 or is there something else we might have missed?

Thank you,

George

**Comment by SteveMacenski** [comment]
I fixed that recently but needs time for the next Humble release to come out to replace the binaries. Sorry about that, 100% my mistake filling in Bloom prompts. 3.4.2 should be placed in Humble the next sync.
