### ISSUE TITLE
Clarification on handling of IMU vs. Odometry data

### ISSUE THREAD

**Issue by ndahn** [cra-ros-pkg/robot_localization#824]
Hello hello,

we have an IMU that integrates data from some other sensors and thus also provides e.g. linear velocities in a custom message type. As this data could not be included in an IMU message, I wrote a node that publishes it as an Odometry message. However, I have some doubts on how handling of IMU data is different from Odometry data in robot_localization. 

I *think* it should work if I publish the Odometry in the "map" frame and use the IMU's frame as the child_frame_id. Would this be correct? I could also feed the IMU data into the localization node as normal and take only the velocity from the odometry, but that seems less elegant. 

Hope you can shed some light on this :) Thanks in advance!
Nikolas

**Comment by ayrton04** [comment]
Would you please ask this on robotics.stackexchange.com?
