### ISSUE TITLE
Can I use ekf_localization using only IMU?

### ISSUE THREAD

**Issue by mildro16** [cra-ros-pkg/robot_localization#837]
Hi! I have a question about ekf_localization.
According to statment, it needs not only IMU topic also Odometry topic, and so on to use ekf_localization.
However, I have only IMU topics, without odometry.
Can I track position of robot without Odometry?
If it can't, I want to know other package which can track position of robot using only IMU sensors.

**Comment by ayrton04** [comment]
Please ask questions on robotics.stackexchange.com. I don't think there are any state estimation packages out there that will let you track pose (accurately) using just an IMU. The double integration of acceleration data will always result in a runaway state estimate.
