### ISSUE TITLE
Performance using just an IMU

### ISSUE THREAD

**Issue by ishaanamahajan** [cra-ros-pkg/robot_localization#847]
This is how my ekf config looks like. I am trying to use just an IMU (Wheeltec n100), and I got some really good results a while back (attached below). For some reason I am not able to replicate a behavior anywhere close to that anymore. Is there something I am missing on how the package works?
![Screenshot from 2023-11-27 16-54-29](https://github.com/cra-ros-pkg/robot_localization/assets/73236968/f313d5bb-11a7-4d25-97d4-b5da52ec5f59)

![Screenshot from 2023-11-07 14-04-03](https://github.com/cra-ros-pkg/robot_localization/assets/73236968/2ff45678-4609-4765-9ed5-bde0bb461af8)

Thank you for the help!

**Comment by ayrton04** [comment]
Please ask questions on robotics.stackexchange.com. This package has never worked well with only IMU data, and I can't imagine any package would. The double-integration of acceleration data will always result in runaway velocity. You need, at minimum, a velocity reference.
