### ISSUE TITLE
Can I get a velocity estimate with using just a GPS and an IMU?

### ISSUE THREAD

**Issue by ishaanamahajan** [cra-ros-pkg/robot_localization#849]
Hi, 

I asked this question on [here](https://robotics.stackexchange.com/questions/105826/can-robot-localization-package-work-well-with-just-an-imu-and-a-gps) but have not heard back yet. I am using the package to get a velocity estimate. Can I just use an IMU and a GPS to do so (no odometer), since an EKF is capable to do state-estimation using IMU and GPS data. 

Thanks!

**Comment by ayrton04** [comment]
If you've asked on Stack Exchange, that's the correct thing to do. I'd ask that we not cross-post questions here. Thanks!
