### ISSUE TITLE
The NavSat_transform_node publish topic but no msgs received.

### ISSUE THREAD

**Issue by gyiptgyipt** [cra-ros-pkg/robot_localization#850]
Hello, I am trying to fuse IMU(mpu6050) and gps(Neo7m) modules. I used madgwick filter from [imu_tools](https://github.com/CCNYRoboticsLab/imu_tools) package for imu. I have a problem with navsat_transform_node that publish the topic (navsat_transform_node) but  no messages were provided. 

My rqt_graph is as follow: 
![rqt_graph](https://github.com/cra-ros-pkg/robot_localization/assets/100279699/53deec67-3c72-45bf-be7d-f00d3dff639c)

When I echo topic of imu:
![imu_topic](https://github.com/cra-ros-pkg/robot_localization/assets/100279699/f02960c5-00e0-4654-823f-6fc4fdf9b0a5)
(frame id : imu_frame_bridge)

My gps topic shows:
![gps_topic](https://github.com/cra-ros-pkg/robot_localization/assets/100279699/3451e4e3-12fc-4b2e-be07-e4f675b637ad)

my launch file(ekf_global.launch.py)  is: 
`#!/usr/bin/env python3
import os

from ament_index_python.packages import get_package_share_directory

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node

def generate_launch_description():
    package_dir = get_package_share_directory('navfuse')
    config_file = os.path.join(package_dir, 'config', 'ekf_global.yaml')

    use_sim_time = LaunchConfiguration('use_sim_time')

    return LaunchDescription([
        DeclareLaunchArgument(
            'use_sim_time', default_value='false',
            description='Use clock topic (from bagfile) if true'),

        Node(
            package='tf2_ros',
            executable='static_transform_publisher',
            name='map_link',
            output='screen',
            arguments=['0', '0', '0', '0', '0', '0', '1', 'map', 'odom']
        ),
        Node(
            package='tf2_ros',
            executable='static_transform_publisher',
            name='odom_link',
            output='screen',
            arguments=['0', '0', '0', '0', '0', '0', '1', 'odom', 'base_link']
        ),

        Node(
            package='tf2_ros',
            executable='static_transform_publisher',
            name='bl_gps',
            output='screen',
            arguments=['0', '0', '0', '0', '0', '0', '1', 'base_link', 'gps_link']
        ),
        # EKF node for global odometry
        Node(
            name='ekf_global_odom',
            package='robot_localization',
            executable='ekf_node',
            parameters=[config_file,
                        {'use_sim_time': True}],
            output = 'screen',
            # Subscriptions (in yaml):
            #   odom0: odometry/gps (from navsat node)
            #   odom1: base_controller/odom
            #   imu0:  imu/data
            # Publishes odometry/global
            remappings=[('/odometry/filtered', '/odometry/global')]
            
        ),

        # Turn GPS fix into odometry message for EKF
        Node(
            name='navsat_transform_node',
            package='robot_localization',
            executable='navsat_transform_node',
            # yaw_offset - corrects to make IMU read 0 when facing East
            # magnetic_declination - see http://www.ngdc.noaa.gov/geomag-web
            # zero_altitude - pretends the world is flat
            # use_odometry_yaw - false, use IMU yaw
            parameters=[{'yaw_offset': 0.0,
                         'magnetic_declination_radians': 0.0,
                         'broadcast_cartesian_transform': True,
                         'zero_altitude': True,
                         'publish_filtered_gps': True,
                         'frequency': 10.0,
                         'use_odometry_yaw': False}],
            output = 'screen',                                                            
            # Subscribes to imu/data, gps/fix, odometry/global
            # Publishes gps/filtered, odometry/gps
            remappings=[('/odometry/filtered', '/odometry/global'),
                        ('/imu','/imu/data'),
                        ('/gps/fix','/fix')]
        )
    ])
`

and my config file (ekf_global.yaml) is:
`ekf_global_odom:
  ros__parameters:
    two_d_mode: true
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map
    map_frame: map

    two_d_mode: true
    publish_tf: true

    frequency: 50.0

    odom0: /odometry/gps
    odom0_config: [true,  true,  false,   # x,   y,   z
                   false, false, false,   # r,   p,   w (yaw)
                   false, false, false,   # dx,  dy,  dz
                   false, false, false,   # dr,  dp,  dw
                   false, false, false]   # ddx, ddy, ddz
    odom0_differential: false
    odom0_queue_size: 10

    # odom1: /base_controller/odom
    # odom1_config: [false, false, false,   # x,   y,   z
    #                false, false, false,   # r,   p,   w (yaw)
    #                true,  true,  true,    # dx,  dy,  dz
    #                false, false, true,    # dr,  dp,  dw
    #                false, false, false]   # ddx, ddy, ddz
    # odom1_differential: false
    # odom1_queue_size: 10

    # (note this is not raw IMU, but output from madgwick filter)
    imu0: /imu/data
    imu0_config: [false, false, false,   # x,   y,   z
                  true,  true,  true,    # r,   p,   w (yaw)
                  false, false, false,   # dx,  dy,  dz
                  true,  true,  true,    # dr,  dp,  dw
                  true,  true,  true,]   # ddx, ddy, ddz
    imu0_differential: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true
`

My question is that for fusing the imu and gps, frame_ids have to be imu_link and gps_link? 

Sorry for the basic question, I am new in ros2. 
Thanks for your time.

**Comment by ayrton04** [comment]
Hi, can you please ask this on robotics.stackexchange.com?
