### ISSUE TITLE
 Separating the msgs from the package

### ISSUE THREAD

**Issue by rafal-gorecki** [cra-ros-pkg/robot_localization#859]
If it would not be a big problem for you, I would ask you to split the package into `robot-localization-msgs` and `robot-localization`.

Why?
When exchanging messages on multiple devices, it is necessary to download the entire package, which weighs much more (about 150 Mb) than the services needed for reading and sending.

Regards

**Comment by ayrton04** [comment]
This package is being deprecated, so I am reluctant to make that large a change to it.

You could always create your own package with a message structure that is identical to the messages in this package. The MD5 sums will be the same, so you'll be able to receive the message on the other end.

**Comment by rafal-gorecki** [comment]
Thank you for your answer
