### ISSUE TITLE
localization in pivot turn

### ISSUE THREAD

**Issue by mamoru1126** [cra-ros-pkg/robot_localization#868]
Hello, I have a question about position estimation when a robot performs pivot turn.
In pivot turn, it is ideal for only the robot's yaw angle to change, while the x and y positions remain constant.
But, I have found that during actual pivot turn of the robot, the the estimated x and y values from EKF change by about 1 meter.
(the estimated x and y values from wheel odometry remain unchanged)
After completing the pivot turn, the estimated  x and y values from EKF converge to their initial values.

**To Reproduce**
1. Set up the robot according to the instructions on the following website
https://docs.ros.org/en/melodic/api/robot_localization/html/index.html

2. launch robot_localization and pivot the robot on the spot.

**Expected behavior**
the estimation results for x and y remain unchanged with the EKF, while only the yaw angle of the robot changes.

**Desktop (please complete the following information):**
 - OS : ubuntu20.04
 - ROS Distribution : noetic
 - `robot_localization` Package Version :  latest (using ekf and navsat)
 - GNSS Device ZED-F9P (output rate 5Hz)

**Comment by ayrton04** [comment]
Thanks for the question. However, all questions should be directed to robotics.stackexchange.com.
