### ISSUE TITLE
Z- drift in two_d_mode

### ISSUE THREAD

**Issue by anath93** [cra-ros-pkg/robot_localization#870]
**Describe the bug**
Shouldn't the z, roll, pitch and yaw should be 0 ?

**Expected behavior**
z, roll, pitch and yaw to be 0.0
https://github.com/cra-ros-pkg/robot_localization/blob/galactic-devel/src/ros_filter.cpp#L336

**Screenshots**
![image](https://github.com/cra-ros-pkg/robot_localization/assets/130472005/56d61bfc-9fa3-4d1d-9a1e-5e8ae2b24393)
![image](https://github.com/cra-ros-pkg/robot_localization/assets/130472005/b52fbdbb-e994-46b8-a08e-9f7f0472bde1)
![image](https://github.com/cra-ros-pkg/robot_localization/assets/130472005/7a101e5e-2d2e-4bc2-846d-45d1f4b96230)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - ROS Distribution: Galactic
 - `robot_localization` Package Version: Binary Package

**Comment by ayrton04** [comment]
Those values _are_ zero. The filter works by providing 0 meausrements with very small covariances for Z, roll, and pitch (and their respective velocities) when you turn on `two_d_mode`. I think we can all agree that `1e-90` is pretty much zero, right?
