### ISSUE TITLE
State and Covariance blow up when a sensor update is delayed/missed. 

### ISSUE THREAD

**Issue by lowellm91** [cra-ros-pkg/robot_localization#871]
# ALL QUESTIONS SHOULD BE DIRECTED TO robotics.stackexchange.com

**Describe the bug**

When fusing multiple odometry sources using differential mode, when an output is missed the state transition matrix, its jacobian and the updated state blow up. Thresholding doesn't seem to filter this out.  

**To Reproduce**

I can't provide the bag file and odometry setup that causes this but basically an odometry source being missed causes system explosion. 

**Expected behavior**

I expected the extreme output to be filtered out via a threshold and the system to update using the existing velocity information. 

**Screenshots**

![Screenshot from 2024-03-19 21-44-11](https://github.com/cra-ros-pkg/robot_localization/assets/152669045/bea229eb-a8ff-47ae-9a67-6804746da39d)

**Desktop (please complete the following information):**
 - OS: Ubuntut 22.04
 - ROS Distribution: Humble
 - `robot_localization` Package Version:3.5.2

**Comment by ayrton04** [comment]
This should be a question. As the template suggests, please direct questions to robotics.stackexchange.com.

**Comment by lowellm91** [comment]
Hi, I believe this is a bug, we think it's related to the system shifting between sim_time and real time when the SLAM node isn't updated fast enough. The thing is even after setting all our nodes to use_sim_time, the problem still persists with the system blowing up. Do you have a suggestion in terms of tracking down if it's a bug?
