### ISSUE TITLE
robot_localization/lib/librl_lib.so: file too short

### ISSUE THREAD

**Issue by hhhhhhwww** [cra-ros-pkg/robot_localization#875]
# ALL QUESTIONS SHOULD BE DIRECTED TO robotics.stackexchange.com

## When asking a question on robotics.stackexchange.com, please include your full EKF config and one sample message from each sensor input**

# THIS PACKAGE WILL SOON BE DEPRECATED. UNLESS SEVERE, BUG REPORTS ARE UNLIKELY TO BE ADDRESSED

**Describe the bug**
ros2 launch robot_localization ukf.launch.py 
[INFO] [launch]: All log files can be found below /home/lxx/.ros/log/2024-03-29-11-09-48-953202-lxx-vm-16130
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [ukf_node-1]: process started with pid [16141]
[ukf_node-1] /opt/ros/humble/lib/robot_localization/ukf_node: error while loading shared libraries: /home/lxx/ros2_localization/install/robot_localization/lib/librl_lib.so: file too short
[ERROR] [ukf_node-1]: process has died [pid 16141, exit code 127, cmd '/opt/ros/humble/lib/robot_localization/ukf_node --ros-args -r __node:=ukf_filter_node --params-file /opt/ros/humble/share/robot_localization/params/ukf.yaml'].

**To Reproduce**
1. ros2 launch robot_localization ukf.launch.py

**Expected behavior**
I want to launch the file,about robot_localization,ekf.launch.py

**Screenshots**
no

**Desktop (please complete the following information):**
 - OS:ubuntu22.04
 - ROS Distribution:ros2
 - `robot_localization` Package Version:humble

**Additional context**
is it a problem colcon build ?

**Comment by ayrton04** [comment]
This looks like a build issue on your machine. As the issue template suggests, please ask questions on robotics.stackexchange.com.
