### ISSUE TITLE
Issues when fusing odometry for Ackermann steered robot

### ISSUE THREAD

**Issue by Rak-r** [cra-ros-pkg/robot_localization#877]
Platform: ROS2 Humble,

I have opened a question on robotics stack exchange. It would be great if somebody could provide any guidance to deal with the problem. 

Reference link: https://robotics.stackexchange.com/questions/110374/issues-while-setting-up-ekf-for-ackermann-steered-robot 
@ayrton04

**Comment by ayrton04** [comment]
Please don't cross post. I will look at your issue when I have time.

**Comment by Rak-r** [comment]
Could you provide any insight about the issue mentioned in the above link. I have been reading about similar setups and trying  but getting a bit confused. @ayrton04

**Comment by ayrton04** [comment]
> I will look at your issue when I have time.

I'm afraid this is still true. I will get to it when I can. Please don't keep asking.
