### ISSUE TITLE
Dynamic Sensor Configuration in Robot Localization

### ISSUE THREAD

**Issue by catcracker** [cra-ros-pkg/robot_localization#889]
Issue:

I am using Robot Localization with ROS 2 and integrating data from multiple sensors into the Extended Kalman Filter (EKF). My concern is about handling situations where one of the sensors loses data temporarily or permanently.

Question:
Can I dynamically adjust sensor configurations using ROS 2 parameter server or _ros2 param set_ cli command? For example, if one sensor loses data, can I modify the parameter /ekf_filter_node_map pose1_config to exclude the affected sensor's data from the EKF fusion? Here’s an example command:
`ros2 param set /ekf_filter_node_map pose1_config "[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]"`
 If dynamic adjustment isn't feasible, what are the recommended approaches? Should I consider setting the covariance of the affected sensor's data to infinity to effectively exclude it from the fusion process?

**Comment by ayrton04** [comment]
Please ask questions on robotics.stackexchange.com. If you already have, please be patient, as my free time for supporting r_l these days is pretty much 0.
