### ISSUE TITLE
The file of "robot_localization_ias13.zip " is can't download

### ISSUE THREAD

**Issue by fjc7** [cra-ros-pkg/robot_localization#893]
When I enter "http://www.cra.com/robot_localization_ias13.zip" in the google, I get some info as follow:
<img width="604" alt="image" src="https://github.com/user-attachments/assets/f111279c-4528-4791-b3f3-0b4195a37aa6">

**Comment by ayrton04** [comment]
I stopped working for Charles River Analytics in 2015, and they no longer host that file on their website. I'm afraid I do not have a copy of it, apologies.

**Comment by fjc7** [comment]
Thanks for your reply, I found some bag files in the test folder.
