### ISSUE TITLE
Difficulty with /set_pose Service Recognition

### ISSUE THREAD

**Issue by zahra370** [cra-ros-pkg/robot_localization#894]
I am attempting to use the set_pose service in ROS, but it is not being recognized. im trying to import using python node, code is given below 
![image](https://github.com/user-attachments/assets/c8891b14-908d-43eb-9bc4-1366fbcfe44f)
rosservice info /set_pose
ERROR: unknown service  

I am having trouble identifying the cause of this issue and would appreciate assistance in resolving it.

**Comment by ayrton04** [comment]
Thanks for the question. However, all questions should be directed to robotics.stackexchange.com. If you ask a question there, please use text and not screenshots.
